(()=>{
const seed=window.ODEKAKE_SEED||{spots:[]},perf=window.KIBUN_PERFORMANCES||{performances:[]},evt=window.KIBUN_EVENTS||{events:[]};
const spots=seed.spots||[],byId=Object.fromEntries(spots.map(s=>[s.spot_id,s]));
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const TYPE={all:'All',performance:'Stage & music',exhibition:'Exhibitions',seasonal:'Seasonal',family:'Family',workshop:'Workshops',festival:'Festivals',experience:'Experiences',show:'Shows'};
const GENRE={ballet:'Ballet',opera:'Opera',musical:'Musical',theater:'Theatre',kabuki:'Kabuki',noh_kyogen:'Noh & Kyogen',classical:'Classical',dance:'Dance',live:'Live music',family:'Family'};
const typeOrder=['all','performance','exhibition','seasonal','family','workshop','festival','experience','show'];
const areas=[['all','All'],['tokyo','Tokyo'],['kanagawa','Kanagawa']];const whens=[['all','All upcoming'],['today','Today'],['7','Next 7 days'],['30','Next 30 days'],['90','Next 90 days']];const audiences=[['all','All'],['family','With kids'],['adult','Adults'],['international','Visitor-friendly']];
let type=new URLSearchParams(location.search).get('type')||'all',area='all',when='all',audience='all';
const localToday=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`},today=localToday();
function parse(s){return new Date(`${s}T00:00:00`)}
function fmt(a,b){const x=parse(a),y=parse(b||a),o={month:'short',day:'numeric'};return a===(b||a)?x.toLocaleDateString('en-US',o):`${x.toLocaleDateString('en-US',o)} – ${y.toLocaleDateString('en-US',o)}`}
function enName(s){return s?.i18n?.en?.name||s?.name||''}
function norm(){const p=(perf.performances||[]).map(x=>({...x,item_kind:'performance',event_type:'performance',audience:(x.tags||[]).includes('family')?['family']:[],venue_label:null}));const e=(evt.events||[]).map(x=>({...x,item_kind:'event'}));return [...p,...e].filter(x=>(x.end_date||x.start_date)>=today).sort((a,b)=>a.start_date.localeCompare(b.start_date)||String(a.title_en||a.title).localeCompare(String(b.title_en||b.title)))}
function isToday(x){if(x.item_kind==='performance')return x.start_date===today&&x.end_date===today;if(x.availability==='specific_dates')return(x.specific_dates||[]).includes(today);if(x.availability==='scheduled_range')return false;return x.start_date<=today&&(x.end_date||x.start_date)>=today}
function withinDays(x,n){const end=new Date();end.setHours(0,0,0,0);end.setDate(end.getDate()+n);return parse(x.start_date)<=end&&parse(x.end_date||x.start_date)>=parse(today)}
function matches(x){const s=byId[x.venue_spot_id]||{};if(type!=='all'&&x.event_type!==type)return false;if(area==='tokyo'&&s.prefecture!=='東京都')return false;if(area==='kanagawa'&&s.prefecture!=='神奈川県')return false;if(when==='today'&&!isToday(x))return false;if(['7','30','90'].includes(when)&&!withinDays(x,Number(when)))return false;if(audience!=='all'){const a=x.audience||[];if(audience==='adult'&&!(a.includes('adult')||x.item_kind==='performance'))return false;if(audience!=='adult'&&!a.includes(audience))return false}const q=$('whatsOnSearch').value.trim().toLowerCase(),hay=[x.title_en,x.title,x.venue_label,enName(s),...(s.aliases||[]),x.schedule_summary_en].filter(Boolean).join(' ').toLowerCase();return !q||hay.includes(q)}
function label(x){return x.item_kind==='performance'?(GENRE[x.genre]||'Stage & music'):(TYPE[x.event_type]||x.event_type)}
function status(x){if(isToday(x))return 'Today';if(x.start_date<=today&&(x.end_date||x.start_date)>=today)return 'On now';return 'Upcoming'}
function card(x){const s=byId[x.venue_spot_id]||{},venue=x.venue_label||enName(s),summary=x.schedule_summary_en||x.schedule_summary||'';return `<article class="performance-hub-card whats-on-card"><div class="performance-date-block"><b>${esc(fmt(x.start_date,x.end_date))}</b><span>${esc(label(x))}</span><em>${esc(status(x))}</em></div><div class="performance-card-copy"><small>${esc(s.i18n?.en?.city||s.city||'')} · ${esc(venue)}</small><h3>${esc(x.title_en||x.title)}</h3>${summary?`<p>${esc(summary)}</p>`:''}<div class="performance-card-tags">${(x.audience||[]).includes('family')?'<span>With kids</span>':''}${x.indoor===true?'<span>Rain-proof</span>':''}${x.reservation_expected===true?'<span>Book ahead</span>':''}</div></div><div class="performance-card-actions"><a class="outline-btn" href="/en/?spot=${encodeURIComponent(x.venue_spot_id)}&source=whats_on">See place</a><a class="primary-link" href="${esc(x.official_url||s.official_url||'#')}" target="_blank" rel="noopener">Official info →</a></div></article>`}
function chips(root,items,current,key){root.innerHTML=items.map(([k,l])=>`<button type="button" class="performance-filter-chip ${current===k?'active':''}" data-${key}="${k}">${l}</button>`).join('')}
function renderFilters(){chips($('whatsOnTypeFilters'),typeOrder.map(k=>[k,TYPE[k]]),type,'type');chips($('whatsOnAreaFilters'),areas,area,'area');chips($('whatsOnWhenFilters'),whens,when,'when');chips($('whatsOnAudienceFilters'),audiences,audience,'audience');document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{type=b.dataset.type;renderFilters();render()});document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{area=b.dataset.area;renderFilters();render()});document.querySelectorAll('[data-when]').forEach(b=>b.onclick=()=>{when=b.dataset.when;renderFilters();render()});document.querySelectorAll('[data-audience]').forEach(b=>b.onclick=()=>{audience=b.dataset.audience;renderFilters();render()})}
function render(){const items=norm().filter(matches);$('whatsOnCount').textContent=`${items.length} things to do`;$('whatsOnGrid').innerHTML=items.map(card).join('');$('whatsOnEmpty').hidden=items.length>0}
$('whatsOnSearch').addEventListener('input',render);renderFilters();render();
})();
