(()=>{
const seed=window.ODEKAKE_SEED||{spots:[]},dataset=window.KIBUN_PERFORMANCES||{metadata:{genres:{}},performances:[]};
const spots=seed.spots||[],byId=Object.fromEntries(spots.map(s=>[s.spot_id,s]));
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const genreLabels={all:'すべて',ballet:'バレエ',opera:'オペラ',musical:'ミュージカル',theater:'演劇',kabuki:'歌舞伎',noh_kyogen:'能・狂言',classical:'クラシック',dance:'ダンス',live:'ライブ',family:'親子向け'};
const genreOrder=['all','ballet','opera','musical','theater','kabuki','noh_kyogen','classical','dance','live','family'];
const areas=[['all','すべて'],['tokyo','東京'],['kanagawa','神奈川']];const whens=[['all','今後すべて'],['30','30日以内'],['90','90日以内']];
let genre=new URLSearchParams(location.search).get('genre')||'all',area=new URLSearchParams(location.search).get('area')||'all',when='all';
const localToday=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const today=localToday();
function parse(s){return new Date(`${s}T00:00:00`)}
function fmt(start,end){const a=parse(start),b=parse(end||start);const md=d=>`${d.getMonth()+1}.${d.getDate()}`;return start===(end||start)?`${a.getMonth()+1}月${a.getDate()}日`:a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()?`${a.getMonth()+1}月${a.getDate()}日–${b.getDate()}日`:`${md(a)}–${md(b)}`}
function upcoming(){return dataset.performances.filter(p=>(p.end_date||p.start_date)>=today).sort((a,b)=>a.start_date.localeCompare(b.start_date)||a.title.localeCompare(b.title))}
function matches(p){const s=byId[p.venue_spot_id]||{};if(genre!=='all'&&p.genre!==genre)return false;if(area==='tokyo'&&s.prefecture!=='東京都')return false;if(area==='kanagawa'&&s.prefecture!=='神奈川県')return false;if(when!=='all'){const limit=new Date();limit.setHours(0,0,0,0);limit.setDate(limit.getDate()+Number(when));if(parse(p.start_date)>limit)return false;}const q=$('performanceSearch').value.trim().toLowerCase();return !q||`${p.title} ${p.title_en||''} ${s.name||''} ${(s.aliases||[]).join(' ')}`.toLowerCase().includes(q)}
function renderFilters(){ $('performanceGenreFilters').innerHTML=genreOrder.map(k=>`<button type="button" class="performance-filter-chip ${genre===k?'active':''}" data-genre="${k}">${genreLabels[k]}</button>`).join('');$('performanceAreaFilters').innerHTML=areas.map(([k,l])=>`<button type="button" class="performance-filter-chip ${area===k?'active':''}" data-area="${k}">${l}</button>`).join('');$('performanceWhenFilters').innerHTML=whens.map(([k,l])=>`<button type="button" class="performance-filter-chip ${when===k?'active':''}" data-when="${k}">${l}</button>`).join('');document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{genre=b.dataset.genre;renderFilters();render()});document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{area=b.dataset.area;renderFilters();render()});document.querySelectorAll('[data-when]').forEach(b=>b.onclick=()=>{when=b.dataset.when;renderFilters();render()})}
function card(p){const s=byId[p.venue_spot_id]||{},slug=s.slug||s.spot_id;return `<article class="performance-hub-card"><div class="performance-date-block"><b>${esc(fmt(p.start_date,p.end_date))}</b><span>${esc(genreLabels[p.genre]||p.genre)}</span></div><div class="performance-card-copy"><small>${esc(s.city||'')} · ${esc(s.name||'')}</small><h3>${esc(p.title)}</h3>${p.schedule_summary?`<p>${esc(p.schedule_summary)}</p>`:''}<div class="performance-card-tags">${p.duration_minutes?`<span>約${Math.round(p.duration_minutes/10)/6}時間</span>`:''}${p.language_note?`<span>${esc(p.language_note)}</span>`:''}${p.age_note?`<span>${esc(p.age_note)}</span>`:''}${p.childcare===true?'<span>託児情報あり</span>':''}</div></div><div class="performance-card-actions"><a class="outline-btn" href="/?spot=${encodeURIComponent(s.spot_id)}&source=performance">劇場を見る</a><a class="primary-link" href="${esc(p.official_url||s.official_url||'#')}" target="_blank" rel="noopener">公式で確認 →</a></div></article>`}
function render(){const items=upcoming().filter(matches);$('performanceCount').textContent=`${items.length}公演`;$('performanceGrid').innerHTML=items.map(card).join('');$('performanceEmpty').hidden=items.length>0}
$('performanceSearch').addEventListener('input',render);renderFilters();render();
})();
