const seed=window.ODEKAKE_SEED;const {recommend,baseScores}=window.OdekakeRecommender;
const VIBE_UI={cool:['🧊','涼みたい','暑さから逃げたい'],nature:['🌿','自然に浸りたい','緑・山・川へ'],extraordinary:['✨','非日常を味わいたい','いつもと違う一日'],culture:['🏛️','文化にふれたい','アート・音楽・歴史'],waterside:['🌊','水辺へ行きたい','海・川・湖のそばへ'],animals:['🐾','生きものに会いたい','動物・魚と出会う'],creative:['🎨','何か作りたい','音・工作・表現'],food:['🍓','おいしい体験がしたい','食べる・採る・作る'],active:['🏃','思いっきり遊びたい','身体を動かす'],relax:['🛋️','のんびりしたい','頑張らない一日']};
const AUDIENCE_UI={family:['👶','子どもと'],partner:['♡','パートナーと'],solo:['◯','ひとり'],friends:['👥','友だちと']};
const vibeKeys=Object.keys(VIBE_UI);let selectedVibes=[],selectedAudience=localStorage.getItem('kibun-audience')||'family',lastResult=null,currentOrigin=null,lastTravelProvider=null;let favorites=new Set(JSON.parse(localStorage.getItem('kibun-favorites')||'[]'));
const $=id=>document.getElementById(id),vibeGrid=$('vibeGrid'),recommendBtn=$('recommendBtn'),resultsSection=$('resultsSection'),resultsGrid=$('resultsGrid'),warningBox=$('coverageWarning'),dialog=$('spotDialog'),trendingGrid=$('trendingGrid');
function renderAudience(){const el=$('audiencePicker');el.innerHTML=Object.entries(AUDIENCE_UI).map(([k,[ic,label]])=>`<button type="button" class="audience-chip ${k===selectedAudience?'selected':''}" data-audience="${k}" aria-pressed="${k===selectedAudience}"><span>${ic}</span>${label}</button>`).join('');el.querySelectorAll('[data-audience]').forEach(b=>b.addEventListener('click',()=>{selectedAudience=b.dataset.audience;localStorage.setItem('kibun-audience',selectedAudience);renderAudience();updateAudienceUi();}));}
function updateAudienceUi(){$('ageField').hidden=selectedAudience!=='family';$('resultsHeading').innerHTML=selectedAudience==='family'?'今日のふたり／家族なら、<br>この3つ。':selectedAudience==='partner'?'ふたりの今日なら、<br>この3つ。':selectedAudience==='solo'?'ひとりの今日なら、<br>この3つ。':'みんなの今日なら、<br>この3つ。';}
function renderVibes(){vibeGrid.innerHTML=vibeKeys.map(k=>{const [e,n,d]=VIBE_UI[k];return `<button class="vibe-card ${selectedVibes.includes(k)?'selected':''}" data-vibe="${k}" type="button" aria-pressed="${selectedVibes.includes(k)}"><span class="vibe-emoji">${e}</span><span class="vibe-text"><span class="vibe-name">${n}</span><span class="vibe-desc">${d}</span></span></button>`}).join('');vibeGrid.querySelectorAll('.vibe-card').forEach(b=>b.addEventListener('click',()=>toggleVibe(b.dataset.vibe)));updateSelectionUi();}
function toggleVibe(k){if(selectedVibes.includes(k))selectedVibes=selectedVibes.filter(v=>v!==k);else if(selectedVibes.length<3)selectedVibes.push(k);else selectedVibes=[...selectedVibes.slice(0,2),k];renderVibes();}
function updateSelectionUi(){$('selectedHint').textContent=selectedVibes.length?`${selectedVibes.length}/3 選択中${selectedVibes.length===3?' · これで十分！':' · もう少し重ねてもOK'}`:'まずは気分を1つ選んでください';$('clearVibes').hidden=!selectedVibes.length;recommendBtn.disabled=!selectedVibes.length;}
function context(extra={}){const ageVal=$('ageSelect').value,max=$('travelLimitSelect').value;return {selectedVibes:[...selectedVibes],audience:selectedAudience,childAgeMonths:selectedAudience==='family'&&ageVal!==''?Number(ageVal):null,weather:$('weatherSelect').value,availableMinutes:Number($('timeSelect').value),maxTravelMinutes:max?Number(max):null,...extra};}
function vibeLabel(k){return VIBE_UI[k]?.[1]||k}function vibeEmoji(k){return VIBE_UI[k]?.[0]||'•'}function findSpot(id){return seed.spots.find(s=>s.spot_id===id)}function buzzScore(s){return Number(s?.buzz?.score||0)}
function buzzBadge(s){return buzzScore(s)>=90?`<span class="buzz-badge">🔥 話題 ${Math.round(buzzScore(s))}</span>`:''}
function imageBadge(i){return !i||i.type==='photo'?'':`<span class="image-badge">${i.label||'イメージ'}</span>`}function imageCredit(i,compact=false){if(!i)return'';if(i.type==='photo'){if(i.credit_required===false||!i.credit)return'';const label=[i.credit,i.license].filter(Boolean).join(' · '),cls=compact?'image-credit compact':'image-credit detail-credit';return i.source_url?`<a class="${cls}" href="${i.source_url}" target="_blank" rel="noopener">Photo: ${label}</a>`:`<span class="${cls}">Photo: ${label}</span>`;}return compact?'':`<p class="image-note">※ ${i.credit||'生成イメージ'}。実在施設の正確な外観・内観を示すものではありません。</p>`;}
function imageBlock(s,variant='card'){const i=s.hero_image;if(!i?.url)return `<div class="${variant}-image image-fallback"><span>${vibeEmoji(Object.entries(s.vibes_seed||{}).sort((a,b)=>b[1]-a[1])[0]?.[0])}</span></div>`;return `<div class="${variant}-image image-shell" data-media-spot="${s.spot_id}"><img src="${i.url}" alt="${i.alt||s.name}" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.classList.add('image-fallback');this.remove()">${imageBadge(i)}${variant==='card'?imageCredit(i,true):''}</div>`;}
function googleAuthorHtml(authors=[],compact=false){
  if(compact){const a=authors[0];return a?.displayName?`<span class="gmp-author-name">${a.displayName}</span>`:'';}
  if(!authors.length)return'';
  return `<div class="gmp-authors">${authors.map(a=>`<a class="gmp-author" href="${a.uri||'#'}" target="_blank" rel="noopener">${a.photoUri?`<img src="${a.photoUri}" alt="" loading="lazy">`:''}<span>${a.displayName||'写真投稿者'}</span></a>`).join('')}</div>`;
}
function googleAttributionHtml(p,compact=false){
  const source=p.photoGoogleMapsUri||p.placeGoogleMapsUri||'#';
  if(compact)return `<a class="gmp-attribution compact" href="${source}" target="_blank" rel="noopener" aria-label="Google Mapsで元の写真を見る">${googleAuthorHtml(p.authors||[],true)}<span class="gmp-brand" translate="no">Google Maps</span></a>`;
  return `<div class="gmp-attribution detail">${googleAuthorHtml(p.authors||[],false)}<a class="gmp-source-link" href="${source}" target="_blank" rel="noopener"><span class="gmp-brand" translate="no">Google Maps</span> で元の写真を見る →</a></div>`;
}
async function enhanceOnePlacePhoto(node,root=document){
  if(node.dataset.placeEnhanced)return;const s=findSpot(node.dataset.mediaSpot);if(!s||!window.KibunMedia?.shouldUsePlacePhoto(s))return;
  node.dataset.placeEnhanced='loading';const p=await window.KibunMedia.resolvePlacePhoto(s);if(!p?.photoUri){node.dataset.placeEnhanced='fallback';return;}
  const img=node.querySelector('img');if(img){img.src=p.photoUri;img.alt=`${s.name}の写真`;img.referrerPolicy='no-referrer';}
  node.classList.add('google-places-photo');node.querySelector('.image-badge')?.remove();node.querySelector('.image-credit')?.remove();node.querySelector('.gmp-attribution')?.remove();
  node.insertAdjacentHTML('beforeend',googleAttributionHtml(p,true));
  if(root===dialog){const hero=root.querySelector('.dialog-hero');hero?.querySelector('.image-note,.detail-credit,.gmp-attribution.detail')?.remove();hero?.insertAdjacentHTML('beforeend',googleAttributionHtml(p,false));}
  node.dataset.placeEnhanced='1';
}
function enhancePlacePhotos(root=document){
  if(!window.KIBUN_CONFIG?.placePhotoApiUrl||!window.KIBUN_CONFIG?.placePhotoEnabled)return;
  const nodes=[...root.querySelectorAll('[data-media-spot]')].filter(n=>!n.dataset.placeEnhanced);
  if(!nodes.length)return;
  const max=Number(window.KIBUN_CONFIG?.placePhotoMaxConcurrent||3),queue=[];let active=0;
  const run=()=>{while(active<max&&queue.length){const item=queue.shift();active++;enhanceOnePlacePhoto(item,root).finally(()=>{active--;run();});}};
  const enqueue=n=>{if(!n.dataset.placeQueued){n.dataset.placeQueued='1';queue.push(n);run();}};
  if(!('IntersectionObserver'in window)||root===dialog){nodes.forEach(enqueue);return;}
  const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){io.unobserve(e.target);enqueue(e.target);}})},{rootMargin:'220px'});
  nodes.forEach(n=>io.observe(n));
}
function renderTrending(){if(!trendingGrid)return;const items=[...seed.spots].filter(s=>buzzScore(s)>=90).sort((a,b)=>buzzScore(b)-buzzScore(a)).slice(0,6);trendingGrid.innerHTML=items.map(s=>`<button class="trending-card" type="button" data-trending="${s.spot_id}"><div class="trending-media">${imageBlock(s,'trend')}${buzzBadge(s)}</div><div class="trending-copy"><strong>${s.name}</strong><span>${s.prefecture} · ${s.city}</span><small>${s.public_copy||s.buzz?.reason||''}</small></div></button>`).join('');trendingGrid.querySelectorAll('[data-trending]').forEach(b=>b.addEventListener('click',()=>openSpot(b.dataset.trending)));enhancePlacePhotos(trendingGrid);}
async function useCurrentLocation(){const btn=$('locationBtn'),status=$('locationStatus');btn.disabled=true;status.textContent='取得中…';try{currentOrigin=await window.KibunTravel.getCurrentPosition();status.textContent=`取得済み · ±${Math.round(currentOrigin.accuracy)}m`;btn.textContent='現在地を更新';}catch(e){status.textContent='取得できませんでした';currentOrigin=null;alert('現在地を取得できませんでした。ブラウザの位置情報許可を確認してください。');}finally{btn.disabled=false;}}
async function prepareTravel(ctx){if(!ctx.maxTravelMinutes||!currentOrigin)return {...ctx,maxTravelMinutes:null};const preliminary=seed.spots.map(s=>[s,baseScores(s,{...ctx,maxTravelMinutes:null})]).sort((a,b)=>b[1].overall-a[1].overall).slice(0,Number(window.KIBUN_CONFIG?.travelEstimateCandidateLimit||36)).map(x=>x[0]);$('locationStatus').textContent='所要時間を計算中…';const out=await window.KibunTravel.getTimes(preliminary,currentOrigin,$('travelModeSelect').value);lastTravelProvider=out.provider;$('locationStatus').textContent=`取得済み · ${out.provider==='google_routes'?'実ルート':'概算'}`;return {...ctx,travelMinutesBySpot:out.times,requireKnownTravel:true};}
async function renderRecommendations(){recommendBtn.disabled=true;recommendBtn.classList.add('loading');const base=context();if(base.maxTravelMinutes&&!currentOrigin){await useCurrentLocation();if(!currentOrigin){recommendBtn.disabled=false;recommendBtn.classList.remove('loading');return;}}const ctx=await prepareTravel(base);lastResult=recommend(seed,ctx);warningBox.hidden=!lastResult.coverage_warning;warningBox.textContent=lastResult.coverage_warning||'';if(!lastResult.recommendations.length)resultsGrid.innerHTML=`<article class="result-card empty-result"><div class="empty-icon">🧭</div><h3>この条件、まだ開拓中です。</h3><p class="editorial">条件を少し広げるか、所要時間を長めにしてみてください。</p></article>`;else{resultsGrid.innerHTML=lastResult.recommendations.map(resultCard).join('');wireResultActions();enhancePlacePhotos(resultsGrid);}const note=$('travelResultNote');if(base.maxTravelMinutes&&currentOrigin){note.hidden=false;note.innerHTML=`${$('travelModeSelect').value==='drive'?'車':'公共交通'}・${base.maxTravelMinutes}分以内で絞り込み｜${lastTravelProvider==='google_routes'?'実ルート時間 · <span translate="no">Google Maps</span>':'現在は概算時間'}`;}else note.hidden=true;resultsSection.hidden=false;setTimeout(()=>resultsSection.scrollIntoView({behavior:'smooth',block:'start'}),50);recommendBtn.disabled=false;recommendBtn.classList.remove('loading');}
function resultCard(r){const s=findSpot(r.spot_id),css=r.slot==='best_match'?'best':r.slot==='adventure'?'adventure':'easy',tags=selectedVibes.filter(v=>(s.vibes_seed?.[v]||0)>=50).slice(0,3).map(v=>`<span class="mini-tag">${vibeEmoji(v)} ${vibeLabel(v)}</span>`).join(''),why=(r.why||[]).slice(0,2).map(x=>`<li>${translateReason(x)}</li>`).join(''),isFav=favorites.has(s.spot_id),travel=r.travel_minutes!=null?`<span class="travel-chip">${$('travelModeSelect').value==='drive'?'🚗':'🚃'} ${lastTravelProvider==='google_routes'?'':'約'}${r.travel_minutes}分</span>`:'';return `<article class="result-card ${css}"><div class="card-media">${imageBlock(s,'card')}${buzzBadge(s)}<div class="slot-chip">${r.slot_label}</div>${travel}<div class="match-chip"><span>今日との相性</span><strong>${Math.round(r.scores.overall)}<small>%</small></strong></div></div><div class="card-content"><div class="place-meta"><span>${s.prefecture} · ${s.city}</span><span>${AUDIENCE_UI[selectedAudience][1]}相性 ${Math.round(r.scores.audience)}</span></div><h3>${s.name}</h3><p class="editorial">${s.public_copy||''}</p><div class="vibe-tags">${tags}</div><ul class="why-list">${why}</ul><div class="card-actions"><button class="detail-btn" data-detail="${s.spot_id}">この場所を見る <span>→</span></button><button class="fav-btn ${isFav?'active':''}" data-fav="${s.spot_id}" aria-label="お気に入り">${isFav?'♥':'♡'}</button></div></div></article>`;}
function wireResultActions(){resultsGrid.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openSpot(b.dataset.detail)));resultsGrid.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.fav)));}
function translateReason(t){for(const k of vibeKeys)if(t.startsWith(k+' '))return t.replace(k,vibeLabel(k));return t;}
function instagramIcon(){return `<svg class="instagram-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="17.4" cy="6.7" r="1.1" fill="currentColor"/></svg>`}function getInstagramSocial(s){return(s.social_embeds||[]).find(x=>x.platform==='instagram')||null}function socialSection(s){const x=getInstagramSocial(s);if(!x)return'';const title=x.display_title||'この場所の雰囲気をのぞく',copy=x.preview_copy||'公式Instagramで実際の雰囲気を見てみる。';if(x.reel_url)return `<section class="social-peek"><div class="social-peek-head"><span class="social-brand">${instagramIcon()} Instagram</span><h3>${title}</h3><p>${copy}</p></div><div class="instagram-embed-wrap"><blockquote class="instagram-media" data-instgrm-permalink="${x.reel_url}" data-instgrm-version="14"></blockquote></div><a class="social-fallback-link" href="${x.reel_url}" target="_blank" rel="noopener noreferrer">InstagramでReelを開く →</a></section>`;return `<section class="social-peek"><div class="social-peek-head"><span class="social-brand">${instagramIcon()} Instagram</span><h3>${title}</h3><p>${copy}</p></div><a class="instagram-profile-card" href="${x.account_url}" target="_blank" rel="noopener noreferrer"><span class="instagram-profile-mark">${instagramIcon()}</span><span class="instagram-profile-copy"><strong>${x.account_handle||'公式Instagram'}</strong><small>写真やReelを見る</small></span><span class="instagram-profile-arrow">→</span></a></section>`;}
function processInstagramEmbeds(){if(!document.querySelector('.instagram-media[data-instgrm-permalink]'))return;if(window.instgrm?.Embeds?.process)return window.instgrm.Embeds.process();if(document.querySelector('script[data-kibun-instagram-embed]'))return;const sc=document.createElement('script');sc.async=true;sc.src='https://www.instagram.com/embed.js';sc.dataset.kibunInstagramEmbed='true';sc.onload=()=>window.instgrm?.Embeds?.process?.();document.body.appendChild(sc);}
function currentTravelFor(id){return lastResult?.input?.travelMinutesBySpot?.[id]??null}
function openSpot(id){const s=findSpot(id);if(!s)return;const ranked=Object.entries(s.vibes_seed||{}).sort((a,b)=>b[1]-a[1]).slice(0,6),d=s.dynamic_snapshot||{},travel=currentTravelFor(id),aud=s.audience_fit?.[selectedAudience]??'-';$('dialogContent').innerHTML=`<div class="dialog-media">${imageBlock(s,'dialog')}</div><div class="dialog-hero"><p class="eyebrow">${s.prefecture} · ${s.category_primary}</p><h2>${s.name}</h2><p class="dialog-copy">${s.public_copy||''}</p><div class="info-pills">${travel!=null?`<span class="info-pill strong-pill">${$('travelModeSelect').value==='drive'?'🚗':'🚃'} ${lastTravelProvider==='google_routes'?'':'約'}${travel}分</span>`:''}<span class="info-pill">🕐 滞在 約${Math.round((s.stay_minutes_seed||120)/60*10)/10}時間</span><span class="info-pill">${AUDIENCE_UI[selectedAudience][0]} ${AUDIENCE_UI[selectedAudience][1]} ${aud}</span>${selectedAudience==='family'?`<span class="info-pill">👶 乳幼児 ${s.experience_seed?.baby_fit??'-'}</span>`:''}</div>${imageCredit(s.hero_image)}</div><div class="dialog-body"><h3>この場所に合う気分</h3><div class="vibe-bars">${ranked.map(([k,v])=>`<div class="vibe-bar"><span>${vibeEmoji(k)} ${vibeLabel(k).replace('したい','').replace('行きたい','')}</span><span class="bar-track"><span class="bar-fill" style="display:block;width:${v}%"></span></span><strong>${v}</strong></div>`).join('')}</div><div class="audience-score-box">${Object.entries(AUDIENCE_UI).map(([k,[ic,l]])=>`<span class="audience-score ${k===selectedAudience?'active':''}">${ic} ${l}<strong>${s.audience_fit?.[k]??'-'}</strong></span>`).join('')}</div><div class="fact-box"><h4>行く前に確認</h4><p><strong>営業時間：</strong>${d.opening_hours_text||'要確認'}</p><p><strong>料金：</strong>${d.price_summary||'要確認'}</p><p><strong>予約：</strong>${d.reservation_summary||'要確認'}</p>${d.age_note?`<p><strong>年齢：</strong>${d.age_note}</p>`:''}${d.temporary_note?`<p><strong>臨時情報：</strong>${d.temporary_note}</p>`:''}<p class="freshness">最終確認: ${d.checked_at||'未記録'} ※最新情報は公式サイトで再確認してください。</p></div>${socialSection(s)}<div class="fact-box"><h4>アクセス</h4><p>${s.address}</p><a class="official-link" href="${s.official_url}" target="_blank" rel="noopener">公式サイトを見る →</a></div></div>`;dialog.showModal();requestAnimationFrame(()=>{processInstagramEmbeds();enhancePlacePhotos(dialog);});}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('kibun-favorites',JSON.stringify([...favorites]));$('favoriteCount').textContent=favorites.size;if(lastResult&&!resultsSection.hidden){const y=scrollY;resultsGrid.innerHTML=lastResult.recommendations.map(resultCard).join('');wireResultActions();scrollTo(0,y);}}
$('clearVibes').addEventListener('click',()=>{selectedVibes=[];renderVibes()});recommendBtn.addEventListener('click',renderRecommendations);$('locationBtn').addEventListener('click',useCurrentLocation);$('editBtn').addEventListener('click',()=>document.querySelector('.hero').scrollIntoView({behavior:'smooth'}));$('dialogClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});$('favoritesBtn').addEventListener('click',()=>alert(favorites.size?`お気に入り ${favorites.size}件\n${[...favorites].map(id=>'・'+findSpot(id)?.name).join('\n')}`:'まだお気に入りはありません。'));document.querySelectorAll('.collection-card').forEach(btn=>btn.addEventListener('click',()=>{selectedVibes=btn.dataset.vibes.split(',').slice(0,3);renderVibes();document.querySelector('.hero').scrollIntoView({behavior:'smooth'});}));$('favoriteCount').textContent=favorites.size;renderAudience();updateAudienceUi();renderVibes();renderTrending();