const seed=window.ODEKAKE_SEED;const {recommend,baseScores}=window.OdekakeRecommender;
const VIBE_UI={cool:['🧊','涼しく過ごしたい','暑さから逃げる'],nature:['🌿','自然に浸りたい','緑・山・川へ'],extraordinary:['✨','いつもと違う日にしたい','少し特別な一日'],scenic:['🌅','いい景色を見たい','海・街・緑を眺める'],stroll:['🚶','ぶらぶらしたい','街歩き・寄り道'],relax:['🛋️','のんびりしたい','頑張らない一日'],shopping:['🛍️','買い物を楽しみたい','お店を見て回る'],food:['🍓','おいしいものを楽しみたい','食べる・採る・作る'],culture:['🏛️','文化にふれたい','アート・音楽・歴史'],animals:['🐾','生きものに会いたい','動物・魚と出会う'],creative:['🎨','何か作りたい','音・工作・表現'],active:['🏃','思いっきり遊びたい','身体を動かす'],waterside:['🌊','水辺へ行きたい','海・川・湖のそばへ']};
const VIBE_GROUPS=[['mood','今日はどんな一日にしたい？',['cool','extraordinary','relax']],['activity','今日は何を楽しみたい？',['nature','scenic','stroll','shopping','food','culture','animals','creative','active','waterside']]];
const AUDIENCE_UI={family:['👶','子どもと'],partner:['♡','パートナーと'],solo:['◯','ひとり'],friends:['👥','友だちと']};
const vibeKeys=Object.keys(VIBE_UI);let selectedVibes=[],selectedAudience=localStorage.getItem('kibun-audience')||'family',lastResult=null,currentOrigin=null,lastTravelProvider=null;let favorites=new Set(JSON.parse(localStorage.getItem('kibun-favorites')||'[]'));
const $=id=>document.getElementById(id),vibeGrid=$('vibeGrid'),recommendBtn=$('recommendBtn'),resultsSection=$('resultsSection'),resultsGrid=$('resultsGrid'),warningBox=$('coverageWarning'),dialog=$('spotDialog'),trendingGrid=$('trendingGrid');
function renderAudience(){const el=$('audiencePicker');el.innerHTML=Object.entries(AUDIENCE_UI).map(([k,[ic,label]])=>`<button type="button" class="audience-chip ${k===selectedAudience?'selected':''}" data-audience="${k}" aria-pressed="${k===selectedAudience}"><span>${ic}</span>${label}</button>`).join('');el.querySelectorAll('[data-audience]').forEach(b=>b.addEventListener('click',()=>{selectedAudience=b.dataset.audience;localStorage.setItem('kibun-audience',selectedAudience);renderAudience();updateAudienceUi();}));}
function updateAudienceUi(){$('ageField').hidden=selectedAudience!=='family';$('resultsHeading').innerHTML=selectedAudience==='family'?'子どもとの今日なら、<br>この3つ。':selectedAudience==='partner'?'ふたりの今日なら、<br>この3つ。':selectedAudience==='solo'?'ひとりの今日なら、<br>この3つ。':'みんなの今日なら、<br>この3つ。';const lead=$('audienceLead');if(lead)lead.textContent=selectedAudience==='family'?'年齢や移動の負担も見ながら選びます。':selectedAudience==='partner'?'景色・食・特別感も含めて、ふたり向きに並べます。':selectedAudience==='solo'?'静けさや自分のペースで過ごせるかも重視します。':'一緒に体験できること、食事や盛り上がりやすさも重視します。';}
function renderVibes(){vibeGrid.innerHTML=VIBE_GROUPS.map(([key,title,keys])=>`<section class="vibe-group" data-vibe-group="${key}"><div class="vibe-group-head"><strong>${title}</strong><small>${key==='mood'?'気分・テンションから選ぶ':'やりたいことから選ぶ'}</small></div><div class="vibe-grid">${keys.map(k=>{const [e,n,d]=VIBE_UI[k];return `<button class="vibe-card ${selectedVibes.includes(k)?'selected':''}" data-vibe="${k}" type="button" aria-pressed="${selectedVibes.includes(k)}"><span class="vibe-emoji">${e}</span><span class="vibe-text"><span class="vibe-name">${n}</span><span class="vibe-desc">${d}</span></span></button>`}).join('')}</div></section>`).join('');vibeGrid.querySelectorAll('.vibe-card').forEach(b=>b.addEventListener('click',()=>toggleVibe(b.dataset.vibe)));updateSelectionUi();}
function toggleVibe(k){if(selectedVibes.includes(k))selectedVibes=selectedVibes.filter(v=>v!==k);else if(selectedVibes.length<3)selectedVibes.push(k);else selectedVibes=[...selectedVibes.slice(0,2),k];renderVibes();}
function updateSelectionUi(){$('selectedHint').textContent=selectedVibes.length?`${selectedVibes.length}/3 選択中${selectedVibes.length===3?' · これで十分！':' · もう少し重ねてもOK'}`:'気分や、やりたいことを1つ選んでください';$('clearVibes').hidden=!selectedVibes.length;recommendBtn.disabled=!selectedVibes.length;}
function context(extra={}){const ageVal=$('ageSelect').value,max=$('travelLimitSelect').value;return {selectedVibes:[...selectedVibes],audience:selectedAudience,childAgeMonths:selectedAudience==='family'&&ageVal!==''?Number(ageVal):null,weather:$('weatherSelect').value,availableMinutes:Number($('timeSelect').value),maxTravelMinutes:max?Number(max):null,...extra};}
function vibeLabel(k){return VIBE_UI[k]?.[1]||k}function vibeEmoji(k){return VIBE_UI[k]?.[0]||'•'}function findSpot(id){return seed.spots.find(s=>s.spot_id===id)}function buzzScore(s){return Number(s?.buzz?.score||0)}
function buzzBadge(s){return buzzScore(s)>=90?`<span class="buzz-badge">🔥 話題 ${Math.round(buzzScore(s))}</span>`:''}
function imageBadge(i){return !i||i.type==='photo'?'':`<span class="image-badge">${i.label||'イメージ'}</span>`}function imageCredit(i,compact=false){if(!i)return'';if(i.type==='photo'){if(i.credit_required===false||!i.credit)return'';const label=[i.credit,i.license].filter(Boolean).join(' · '),cls=compact?'image-credit compact':'image-credit detail-credit';return i.source_url?`<a class="${cls}" href="${i.source_url}" target="_blank" rel="noopener">Photo: ${label}</a>`:`<span class="${cls}">Photo: ${label}</span>`;}return compact?'':`<p class="image-note">※ ${i.credit||'生成イメージ'}。実在施設の正確な外観・内観を示すものではありません。</p>`;}
function imageBlock(s,variant='card'){const i=s.hero_image;if(!i?.url)return `<div class="${variant}-image image-fallback"><span>${vibeEmoji(Object.entries(s.vibes_seed||{}).sort((a,b)=>b[1]-a[1])[0]?.[0])}</span></div>`;return `<div class="${variant}-image image-shell" data-media-spot="${s.spot_id}"><img src="${i.url}" alt="${i.alt||s.name}" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.classList.add('image-fallback');this.remove()">${imageBadge(i)}${variant==='card'?imageCredit(i,true):''}</div>`;}
function googleAuthorHtml(authors=[],compact=false){
  if(compact){const a=authors[0];return a?.displayName?`<span class="gmp-author-name">${a.displayName}</span>`:'';}
  if(!authors.length)return'';
  return `<div class="gmp-authors">${authors.map(a=>`<a class="gmp-author" href="${a.uri||'#'}" target="_blank" rel="noopener">${a.photoUri?`<img src="${a.photoUri}" alt="" loading="lazy">`:''}<span>${a.displayName||'写真投稿者'}</span></a>`).join('')}</div>`;
}
function googleAttributionHtml(p,compact=false){
  const source=p.photoGoogleMapsUri||p.placeGoogleMapsUri||'#';
  if(compact)return `<a class="gmp-attribution compact" href="${source}" target="_blank" rel="noopener" aria-label="Google Mapsで元の写真を見る">${googleAuthorHtml(p.authors||[],true)}<span class="gmp-brand" translate="no">Google Maps</span></a>`;
  return `<div class="gmp-attribution detail">${googleAuthorHtml(p.authors||[],false)}<a class="gmp-source-link" href="${source}" target="_blank" rel="noopener"><span class="gmp-brand" translate="no">Google Maps</span> で元の写真を見る →</a></div>`;
}
async function enhanceOnePlacePhoto(node,root=document){
  if(node.dataset.placeEnhanced)return;const s=findSpot(node.dataset.mediaSpot);if(!s||!window.KibunMedia?.shouldUsePlacePhoto(s))return;
  node.dataset.placeEnhanced='loading';const p=await window.KibunMedia.resolvePlacePhoto(s);if(!p?.photoUri){node.dataset.placeEnhanced='fallback';return;}
  const img=node.querySelector('img');if(img){img.src=p.photoUri;img.alt=`${s.name}の写真`;img.referrerPolicy='no-referrer';}
  node.classList.add('google-places-photo');node.querySelector('.image-badge')?.remove();node.querySelector('.image-credit')?.remove();node.querySelector('.gmp-attribution')?.remove();
  node.insertAdjacentHTML('beforeend',googleAttributionHtml(p,true));
  if(root===dialog){const hero=root.querySelector('.dialog-hero');hero?.querySelector('.image-note,.detail-credit,.gmp-attribution.detail')?.remove();hero?.insertAdjacentHTML('beforeend',googleAttributionHtml(p,false));}
  node.dataset.placeEnhanced='1';
}
function enhancePlacePhotos(root=document){
  if(!window.KIBUN_CONFIG?.placePhotoApiUrl||!window.KIBUN_CONFIG?.placePhotoEnabled)return;
  const nodes=[...root.querySelectorAll('[data-media-spot]')].filter(n=>!n.dataset.placeEnhanced);
  if(!nodes.length)return;
  const max=Number(window.KIBUN_CONFIG?.placePhotoMaxConcurrent||3),queue=[];let active=0;
  const run=()=>{while(active<max&&queue.length){const item=queue.shift();active++;enhanceOnePlacePhoto(item,root).finally(()=>{active--;run();});}};
  const enqueue=n=>{if(!n.dataset.placeQueued){n.dataset.placeQueued='1';queue.push(n);run();}};
  if(!('IntersectionObserver'in window)||root===dialog){nodes.forEach(enqueue);return;}
  const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){io.unobserve(e.target);enqueue(e.target);}})},{rootMargin:'220px'});
  nodes.forEach(n=>io.observe(n));
}

const HERO_AUDIT=window.KibunMedia?.auditMode===true;
const AUDIT_REASON_UI={
  low_match:['Google上の施設名と一致しません','検索結果は見つかりましたが、Kibunの施設名との一致度が低いため自動採用を止めています。'],
  place_not_found:['Google Placesで候補が見つかりません','施設名を短くしたり、支店名・港名などGoogle Maps上の名前に変えて再検索してください。'],
  no_photo:['Google側に利用できる写真がありません','別名のPlaceがある場合は検索名を変えると写真が見つかることがあります。'],
  api_error:['Google Places APIでエラーが発生しました','API設定・利用上限・一時的なエラーの可能性があります。少し待って再試行してください。'],
  network_error:['通信に失敗しました','通信状態を確認して、もう一度お試しください。'],
  empty_response:['Googleから応答を取得できませんでした','検索名を変えて再検索してください。']
};
function heroAuditSection(s){
  if(!HERO_AUDIT||!window.KibunMedia?.shouldUsePlacePhoto(s))return'';
  const gp=s.media_strategy?.google_places||{};
  return `<section class="hero-audit" data-hero-audit="${s.spot_id}"><div class="hero-audit-head"><div><span class="audit-kicker">PRIVATE · HERO AUDIT</span><h3>Hero写真を選ぶ</h3><p>Google Placesの候補から、この施設らしさが一番伝わる写真を選びます。取得できない場合は、その場で検索名を変えられます。</p></div><button class="audit-reset" type="button" data-audit-reset="${s.spot_id}">写真を自動に戻す</button></div><div class="hero-audit-place"><label><span>Google Places 検索名</span><input type="text" data-audit-query value="${escapeHtml(gp.query||s.name)}"></label><label class="audit-address-toggle"><input type="checkbox" data-audit-use-address checked> 住所も検索に使う</label><button type="button" data-audit-search>再検索</button><button type="button" class="audit-place-clear" data-audit-place-clear>Place固定を解除</button></div><div class="hero-audit-match"></div><div class="hero-audit-grid"><div class="audit-loading">候補写真を読み込み中…</div></div><div class="hero-audit-status"></div></section>`;
}
function auditAuthorLabel(c){return (c.authors||[]).map(a=>a.displayName).filter(Boolean).join(' / ')||'Google Maps';}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function auditFailureHtml(data){const [title,body]=AUDIT_REASON_UI[data?.reason]||['候補写真を取得できませんでした','検索名を変えて再検索してみてください。'];const matched=data?.matchedPlaceName?`<div class="audit-match-candidate"><small>Google候補</small><strong>${escapeHtml(data.matchedPlaceName)}</strong>${data.matchedAddress?`<span>${escapeHtml(data.matchedAddress)}</span>`:''}</div>`:'';return `<div class="audit-empty"><strong>⚠️ ${title}</strong><p>${body}</p>${matched}</div>`;}
async function loadHeroAudit(s){
  if(!HERO_AUDIT)return;const box=dialog.querySelector(`[data-hero-audit="${s.spot_id}"]`);if(!box)return;
  const grid=box.querySelector('.hero-audit-grid'),status=box.querySelector('.hero-audit-status'),matchBox=box.querySelector('.hero-audit-match'),queryInput=box.querySelector('[data-audit-query]'),useAddressInput=box.querySelector('[data-audit-use-address]');
  const placeSaved=(window.KibunMedia.getAuditPlaceOverrides?.()||{})[s.spot_id];if(placeSaved){queryInput.value=placeSaved.query||queryInput.value;useAddressInput.checked=placeSaved.use_address!==false;}
  let latest=null;
  const render=async(opts={})=>{
    grid.innerHTML='<div class="audit-loading">候補写真を読み込み中…</div>';matchBox.innerHTML='';status.textContent='';
    const data=await window.KibunMedia.resolvePlacePhotoCandidates(s,Number(window.KIBUN_CONFIG?.heroAuditCandidateCount||6),opts);latest=data;
    const fixed=(window.KibunMedia.getAuditPlaceOverrides?.()||{})[s.spot_id];
    if(data?.matchedPlaceName){matchBox.innerHTML=`<div class="audit-place-result ${data.matchConfidence==='low'?'warning':''}"><div><small>Google Places候補 · 一致度 ${escapeHtml(data.matchConfidence||'-')}</small><strong>${escapeHtml(data.matchedPlaceName)}</strong><span>${escapeHtml(data.matchedAddress||'')}</span></div>${data.placeId?`<button type="button" data-audit-fix-place>${fixed?.place_id===data.placeId?'✓ Place固定済み':'このGoogle施設を固定'}</button>`:''}</div>`;}
    if(!data?.candidates?.length){grid.innerHTML=auditFailureHtml(data);if(data?.reason==='low_match'&&data.placeId)status.textContent='検索名を調整するか、「再検索」で候補写真を確認してから施設を固定してください。';bindFix();return;}
    const overrides=window.KibunMedia.getAuditOverrides?.()||{},saved=overrides[s.spot_id],seedOverride=s.media_strategy?.google_places?.photo_index_override;
    grid.innerHTML=data.candidates.map(c=>`<button class="audit-photo ${c.index===saved?'selected':''}" type="button" data-audit-index="${c.index}"><span class="audit-photo-img"><img src="${c.photoUri}" alt="${escapeHtml(s.name)} Hero候補 ${c.index}" loading="lazy" referrerpolicy="no-referrer"><span class="audit-index">#${c.index}</span>${c.index===data.autoSelectedPhotoIndex?'<span class="audit-auto">AUTO</span>':''}</span><span class="audit-photo-meta"><strong>${c.widthPx||'?'}×${c.heightPx||'?'}</strong><small>${escapeHtml(auditAuthorLabel(c))}</small></span></button>`).join('');
    const describe=()=>{const now=(window.KibunMedia.getAuditOverrides?.()||{})[s.spot_id],pf=(window.KibunMedia.getAuditPlaceOverrides?.()||{})[s.spot_id];const photoText=Number.isInteger(now)?`写真 #${now} を選択中`:Number.isInteger(seedOverride)?`seed固定: #${seedOverride}`:`自動選択: #${data.autoSelectedPhotoIndex??'-'}`;status.textContent=`${photoText}${pf?.place_id?' · Google Place固定済み':''}${data.requiresManualConfirmation?' · ⚠️ 一致度LOWなので目視確認必須':''}`;};describe();
    grid.querySelectorAll('[data-audit-index]').forEach(btn=>btn.addEventListener('click',()=>{const idx=Number(btn.dataset.auditIndex),candidate=data.candidates.find(c=>c.index===idx);if(!candidate)return;window.KibunMedia.setAuditOverride(s.spot_id,idx);grid.querySelectorAll('.audit-photo').forEach(x=>x.classList.toggle('selected',x===btn));const media=dialog.querySelector(`[data-media-spot="${s.spot_id}"]`),img=media?.querySelector('img');if(img)img.src=candidate.photoUri;media?.classList.add('google-places-photo');media?.querySelector('.image-badge')?.remove();media?.querySelector('.image-credit')?.remove();media?.querySelector('.gmp-attribution')?.remove();media?.insertAdjacentHTML('beforeend',googleAttributionHtml(candidate,true));const hero=dialog.querySelector('.dialog-hero');hero?.querySelector('.image-note,.detail-credit,.gmp-attribution.detail')?.remove();hero?.insertAdjacentHTML('beforeend',googleAttributionHtml({...candidate,placeGoogleMapsUri:data.placeGoogleMapsUri},false));describe();}));
    bindFix();
    function bindFix(){matchBox.querySelector('[data-audit-fix-place]')?.addEventListener('click',()=>{if(!latest?.placeId)return;window.KibunMedia.setAuditPlaceOverride(s.spot_id,{query:queryInput.value.trim()||s.name,place_id:latest.placeId,matched_name:latest.matchedPlaceName,matched_address:latest.matchedAddress,use_address:useAddressInput.checked});render({query:queryInput.value.trim()||s.name,placeId:latest.placeId,useAddress:useAddressInput.checked,allowLowMatch:true});});}
  };
  box.querySelector('[data-audit-search]')?.addEventListener('click',()=>{window.KibunMedia.clearCandidateCache?.(s.spot_id);render({query:queryInput.value.trim()||s.name,placeId:'',useAddress:useAddressInput.checked,allowLowMatch:true});});
  queryInput?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();box.querySelector('[data-audit-search]')?.click();}});
  box.querySelector('[data-audit-place-clear]')?.addEventListener('click',()=>{window.KibunMedia.setAuditPlaceOverride(s.spot_id,null);queryInput.value=s.media_strategy?.google_places?.query||s.name;useAddressInput.checked=true;render({query:queryInput.value,placeId:'',useAddress:true,allowLowMatch:false});});
  box.querySelector('[data-audit-reset]')?.addEventListener('click',async()=>{window.KibunMedia.setAuditOverride(s.spot_id,null);dialog.close();setTimeout(()=>openSpot(s.spot_id),0);});
  await render({query:queryInput.value.trim()||s.name,placeId:placeSaved?.place_id||s.media_strategy?.google_places?.place_id||'',useAddress:useAddressInput.checked,allowLowMatch:false});
}
function installHeroAuditDock(){
  if(!HERO_AUDIT)return;const dock=document.createElement('aside');dock.className='hero-audit-dock';dock.innerHTML=`<span>🖼 Hero監査 <small>v16</small></span><select id="heroAuditSpotSelect" aria-label="監査するスポット">${seed.spots.map(s=>`<option value="${s.spot_id}">${s.name}</option>`).join('')}</select><button type="button" id="heroAuditOpen">開く</button><button type="button" id="heroAuditExport">設定を書き出す</button>`;document.body.appendChild(dock);
  const sel=dock.querySelector('#heroAuditSpotSelect');dock.querySelector('#heroAuditOpen').addEventListener('click',()=>openSpot(sel.value));dock.querySelector('#heroAuditExport').addEventListener('click',()=>{const payload=JSON.stringify({photo_index_overrides:window.KibunMedia.getAuditOverrides?.()||{},place_overrides:window.KibunMedia.getAuditPlaceOverrides?.()||{}},null,2);const w=window.open('','_blank');if(w){w.document.write(`<meta name="viewport" content="width=device-width"><pre style="white-space:pre-wrap;font:14px/1.5 monospace;padding:20px">${escapeHtml(payload)}</pre>`);w.document.close();}else prompt('Hero audit export',payload);});
}
function renderTrending(){if(!trendingGrid)return;const items=[...seed.spots].filter(s=>buzzScore(s)>=90).sort((a,b)=>buzzScore(b)-buzzScore(a)).slice(0,6);trendingGrid.innerHTML=items.map(s=>`<button class="trending-card" type="button" data-trending="${s.spot_id}"><div class="trending-media">${imageBlock(s,'trend')}${buzzBadge(s)}</div><div class="trending-copy"><strong>${s.name}</strong><span>${s.prefecture} · ${s.city}</span><small>${s.public_copy||s.buzz?.reason||''}</small></div></button>`).join('');trendingGrid.querySelectorAll('[data-trending]').forEach(b=>b.addEventListener('click',()=>openSpot(b.dataset.trending)));enhancePlacePhotos(trendingGrid);}
function locationHelpContent(kind){
  const android=/Android/i.test(navigator.userAgent),ios=/iPhone|iPad|iPod/i.test(navigator.userAgent);
  const steps={
    permission_denied:{title:'位置情報の許可がOFFです',body:android?'アドレスバー左のサイト情報 →「権限」→「位置情報」→「許可」に変更してください。Chrome自体の位置情報権限も必要です。':ios?'iPhoneの「設定」→「プライバシーとセキュリティ」→「位置情報サービス」でブラウザを許可し、サイトを再読み込みしてください。':'ブラウザのサイト設定で、このサイトの位置情報を「許可」に変更してください。'},
    position_unavailable:{title:'現在地を特定できませんでした',body:'端末の位置情報をONにして、Wi‑Fiやモバイル通信が使える状態で再度お試しください。屋内では窓際へ移動すると改善することがあります。'},
    timeout:{title:'現在地の取得に時間がかかっています',body:'通信状況やGPSの状態によって時間がかかることがあります。少し待ってから、もう一度お試しください。'},
    unsupported:{title:'このブラウザでは現在地を使えません',body:'最新版のChrome・Safariなど、位置情報に対応したブラウザで開いてください。'},
    insecure_context:{title:'安全な接続が必要です',body:'位置情報はHTTPSのページでのみ利用できます。Kibunの公開URLから開き直してください。'},
    unknown:{title:'現在地を取得できませんでした',body:'位置情報の設定と通信状況を確認して、もう一度お試しください。'}
  };return steps[kind]||steps.unknown;
}
function hideLocationHelp(){const box=$('locationHelp');if(box){box.hidden=true;box.innerHTML='';}}
function showLocationHelp(error){const box=$('locationHelp');if(!box)return;const info=locationHelpContent(error?.kind||'unknown');box.hidden=false;box.innerHTML=`<div class="location-help-icon">📍</div><div class="location-help-copy"><strong>${info.title}</strong><p>${info.body}</p><div class="location-help-actions"><button type="button" class="location-help-retry" data-location-retry>もう一度試す</button><button type="button" class="location-help-skip" data-location-skip>所要時間なしで続ける</button></div></div>`;box.querySelector('[data-location-retry]')?.addEventListener('click',useCurrentLocation);box.querySelector('[data-location-skip]')?.addEventListener('click',()=>{$('travelLimitSelect').value='';hideLocationHelp();$('locationStatus').textContent='未取得 · 時間指定なし';});}
async function useCurrentLocation(){const btn=$('locationBtn'),status=$('locationStatus');btn.disabled=true;status.textContent='取得中…';hideLocationHelp();try{currentOrigin=await window.KibunTravel.getCurrentPosition();status.textContent=`取得済み · ±${Math.round(currentOrigin.accuracy)}m`;btn.textContent='現在地を更新';hideLocationHelp();return currentOrigin;}catch(e){status.textContent='取得できませんでした';currentOrigin=null;showLocationHelp(e);return null;}finally{btn.disabled=false;}}
async function prepareTravel(ctx){if(!ctx.maxTravelMinutes||!currentOrigin)return {...ctx,maxTravelMinutes:null};const preliminary=seed.spots.map(s=>[s,baseScores(s,{...ctx,maxTravelMinutes:null})]).sort((a,b)=>b[1].overall-a[1].overall).slice(0,Number(window.KIBUN_CONFIG?.travelEstimateCandidateLimit||36)).map(x=>x[0]);$('locationStatus').textContent='所要時間を計算中…';const out=await window.KibunTravel.getTimes(preliminary,currentOrigin,$('travelModeSelect').value);lastTravelProvider=out.provider;$('locationStatus').textContent=`取得済み · ${out.provider==='google_routes'?'実ルート':'概算'}`;return {...ctx,travelMinutesBySpot:out.times,requireKnownTravel:true};}
async function renderRecommendations(){recommendBtn.disabled=true;recommendBtn.classList.add('loading');const base=context();if(base.maxTravelMinutes&&!currentOrigin){await useCurrentLocation();if(!currentOrigin){recommendBtn.disabled=false;recommendBtn.classList.remove('loading');return;}}const ctx=await prepareTravel(base);lastResult=recommend(seed,ctx);warningBox.hidden=!lastResult.coverage_warning;warningBox.textContent=lastResult.coverage_warning||'';if(!lastResult.recommendations.length)resultsGrid.innerHTML=`<article class="result-card empty-result"><div class="empty-icon">🧭</div><h3>この条件、まだ開拓中です。</h3><p class="editorial">条件を少し広げるか、所要時間を長めにしてみてください。</p></article>`;else{resultsGrid.innerHTML=lastResult.recommendations.map(resultCard).join('');wireResultActions();enhancePlacePhotos(resultsGrid);}const note=$('travelResultNote');if(base.maxTravelMinutes&&currentOrigin){note.hidden=false;note.innerHTML=`${$('travelModeSelect').value==='drive'?'車':'公共交通'}・${base.maxTravelMinutes}分以内で絞り込み｜${lastTravelProvider==='google_routes'?'実ルート時間 · <span translate="no">Google Maps</span>':'現在は概算時間'}`;}else note.hidden=true;resultsSection.hidden=false;setTimeout(()=>resultsSection.scrollIntoView({behavior:'smooth',block:'start'}),50);recommendBtn.disabled=false;recommendBtn.classList.remove('loading');}
function audienceLabel(aud=selectedAudience){return aud==='family'?'子どもと行きやすい':aud==='partner'?'ふたりで楽しみやすい':aud==='solo'?'ひとりで過ごしやすい':'みんなで楽しみやすい';}
function audienceCopy(s,aud=selectedAudience){if(s.audience_copy?.[aud])return s.audience_copy[aud];if(aud==='family')return s.public_copy||'';const v=s.vibes_seed||{},e=s.experience_seed||{};if(aud==='partner'){if((v.shopping||0)>=80&&(v.food||0)>=70)return 'お店を見たり食事をしたり、寄り道しながらふたりの時間を作りやすい。';if((v.scenic||0)>=80)return '景色を眺めながら、急ぎすぎずふたりで過ごしたい日に。';if((v.culture||0)>=80)return '展示や建築を一緒に見ながら、自然に会話が生まれるような休日に。';return 'ふたりで気分を変えながら、ゆっくり楽しみやすいスポット。';}if(aud==='solo'){if((e.quietness||0)>=75||(v.relax||0)>=85)return '自分のペースを崩さず、気になったところだけじっくり楽しみやすい。';if((v.culture||0)>=80)return 'ひとりでじっくり見て回りたい日に向く。';if((v.stroll||0)>=80)return '目的を決めすぎず、気ままに歩いて気分転換しやすい。';return '予定を詰めず、自分のペースで楽しみやすいスポット。';}if((v.active||0)>=80||(e.hands_on||0)>=75)return '一緒に体験したり動いたり、友だちと盛り上がりやすい。';if((v.shopping||0)>=80||(v.food||0)>=80)return '見て、食べて、寄り道して。みんなで過ごし方を選びやすい。';return '友だちと話しながら、気軽に一緒の時間を楽しみやすい。';}
function audienceInsight(s,aud=selectedAudience){const e=s.experience_seed||{},v=s.vibes_seed||{},chips=[];if(aud==='family'){if((e.stroller_fit||0)>=80)chips.push('ベビーカー向き');if((e.baby_fit||0)>=80)chips.push('乳幼児と行きやすい');if((e.parent_rest||0)>=75)chips.push('大人も休みやすい');}else if(aud==='partner'){if((v.scenic||0)>=80)chips.push('景色を楽しめる');if((v.food||0)>=80)chips.push('食事も楽しみやすい');if((v.relax||0)>=80)chips.push('ゆっくり話せる');if((s.adult_enjoyment_seed||0)>=85)chips.push('大人満足度高め');}else if(aud==='solo'){if((e.quietness||0)>=75)chips.push('静かに過ごしやすい');if((e.planning_friction||50)<=25)chips.push('ふらっと行きやすい');if((v.culture||0)>=80)chips.push('じっくり見られる');if((v.stroll||0)>=80)chips.push('気ままに歩ける');}else{if((e.hands_on||0)>=75)chips.push('一緒に体験');if((v.food||0)>=80)chips.push('食事も楽しめる');if((v.shopping||0)>=80)chips.push('見て回れる');if((v.active||0)>=80)chips.push('盛り上がりやすい');}return chips.slice(0,3);}
function resultCard(r){const s=findSpot(r.spot_id),css=r.slot==='best_match'?'best':r.slot==='adventure'?'adventure':'easy',tags=selectedVibes.filter(v=>(s.vibes_seed?.[v]||0)>=50).slice(0,3).map(v=>`<span class="mini-tag">${vibeEmoji(v)} ${vibeLabel(v)}</span>`).join(''),why=(r.why||[]).slice(0,2).map(x=>`<li>${translateReason(x)}</li>`).join(''),isFav=favorites.has(s.spot_id),travel=r.travel_minutes!=null?`<span class="travel-chip">${$('travelModeSelect').value==='drive'?'🚗':'🚃'} ${lastTravelProvider==='google_routes'?'':'約'}${r.travel_minutes}分</span>`:'';return `<article class="result-card ${css}"><div class="card-media">${imageBlock(s,'card')}${buzzBadge(s)}<div class="slot-chip">${r.slot_label}</div>${travel}<div class="match-chip"><span>今日との相性</span><strong>${Math.round(r.scores.overall)}<small>%</small></strong></div></div><div class="card-content"><div class="place-meta"><span>${s.prefecture} · ${s.city}</span><span>${AUDIENCE_UI[selectedAudience][0]} ${audienceLabel()}</span></div><h3>${s.name}</h3><p class="editorial">${audienceCopy(s)}</p><div class="vibe-tags">${tags}</div><ul class="why-list">${why}</ul><div class="card-actions"><button class="detail-btn" data-detail="${s.spot_id}">この場所を見る <span>→</span></button><button class="fav-btn ${isFav?'active':''}" data-fav="${s.spot_id}" aria-label="お気に入り">${isFav?'♥':'♡'}</button></div></div></article>`;}
function wireResultActions(){resultsGrid.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openSpot(b.dataset.detail)));resultsGrid.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.fav)));}
function translateReason(t){for(const k of vibeKeys)if(t.startsWith(k+' '))return t.replace(k,vibeLabel(k));return t;}
function instagramIcon(){return `<svg class="instagram-icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="17.4" cy="6.7" r="1.1" fill="currentColor"/></svg>`}function getInstagramSocial(s){return(s.social_embeds||[]).find(x=>x.platform==='instagram')||null}function socialSection(s){const x=getInstagramSocial(s);if(!x)return'';const title=x.display_title||'この場所の雰囲気をのぞく',copy=x.preview_copy||'公式Instagramで実際の雰囲気を見てみる。';if(x.reel_url)return `<section class="social-peek"><div class="social-peek-head"><span class="social-brand">${instagramIcon()} Instagram</span><h3>${title}</h3><p>${copy}</p></div><div class="instagram-embed-wrap"><blockquote class="instagram-media" data-instgrm-permalink="${x.reel_url}" data-instgrm-version="14"></blockquote></div><a class="social-fallback-link" href="${x.reel_url}" target="_blank" rel="noopener noreferrer">InstagramでReelを開く →</a></section>`;return `<section class="social-peek"><div class="social-peek-head"><span class="social-brand">${instagramIcon()} Instagram</span><h3>${title}</h3><p>${copy}</p></div><a class="instagram-profile-card" href="${x.account_url}" target="_blank" rel="noopener noreferrer"><span class="instagram-profile-mark">${instagramIcon()}</span><span class="instagram-profile-copy"><strong>${x.account_handle||'公式Instagram'}</strong><small>写真やReelを見る</small></span><span class="instagram-profile-arrow">→</span></a></section>`;}
function processInstagramEmbeds(){if(!document.querySelector('.instagram-media[data-instgrm-permalink]'))return;if(window.instgrm?.Embeds?.process)return window.instgrm.Embeds.process();if(document.querySelector('script[data-kibun-instagram-embed]'))return;const sc=document.createElement('script');sc.async=true;sc.src='https://www.instagram.com/embed.js';sc.dataset.kibunInstagramEmbed='true';sc.onload=()=>window.instgrm?.Embeds?.process?.();document.body.appendChild(sc);}
function currentTravelFor(id){return lastResult?.input?.travelMinutesBySpot?.[id]??null}
function openSpot(id){const s=findSpot(id);if(!s)return;const ranked=Object.entries(s.vibes_seed||{}).sort((a,b)=>b[1]-a[1]).slice(0,7),d=s.dynamic_snapshot||{},travel=currentTravelFor(id),aud=s.audience_fit?.[selectedAudience]??'-',insights=audienceInsight(s);$('dialogContent').innerHTML=`<div class="dialog-media">${imageBlock(s,'dialog')}</div><div class="dialog-hero"><p class="eyebrow">${s.prefecture} · ${s.category_primary}</p><h2>${s.name}</h2><p class="dialog-copy">${audienceCopy(s)}</p><div class="info-pills">${travel!=null?`<span class="info-pill strong-pill">${$('travelModeSelect').value==='drive'?'🚗':'🚃'} ${lastTravelProvider==='google_routes'?'':'約'}${travel}分</span>`:''}<span class="info-pill">🕐 滞在 約${Math.round((s.stay_minutes_seed||120)/60*10)/10}時間</span><span class="info-pill">${AUDIENCE_UI[selectedAudience][0]} ${audienceLabel()} ${aud}</span>${selectedAudience==='family'?`<span class="info-pill">👶 乳幼児 ${s.experience_seed?.baby_fit??'-'}</span>`:''}</div>${imageCredit(s.hero_image)}</div><div class="dialog-body"><section class="audience-detail"><p class="eyebrow">FOR ${selectedAudience.toUpperCase()}</p><h3>${selectedAudience==='family'?'子どもと行くなら':selectedAudience==='partner'?'ふたりで行くなら':selectedAudience==='solo'?'ひとりで行くなら':'友だちと行くなら'}</h3><div class="audience-insight-chips">${insights.map(x=>`<span>${x}</span>`).join('')||'<span>気分との相性を重視</span>'}</div></section><h3>この場所に合う気分・楽しみ方</h3><div class="vibe-bars">${ranked.map(([k,v])=>`<div class="vibe-bar"><span>${vibeEmoji(k)} ${vibeLabel(k).replace('したい','').replace('行きたい','').replace('楽しみたい','')}</span><span class="bar-track"><span class="bar-fill" style="display:block;width:${v}%"></span></span><strong>${v}</strong></div>`).join('')}</div><div class="fact-box"><h4>行く前に確認</h4><p><strong>営業時間：</strong>${d.opening_hours_text||'要確認'}</p><p><strong>料金：</strong>${d.price_summary||'要確認'}</p><p><strong>予約：</strong>${d.reservation_summary||'要確認'}</p>${selectedAudience==='family'&&d.age_note?`<p><strong>子ども：</strong>${d.age_note}</p>`:''}${d.temporary_note?`<p><strong>臨時情報：</strong>${d.temporary_note}</p>`:''}<p class="freshness">最終確認: ${d.checked_at||'未記録'} ※最新情報は公式サイトで再確認してください。</p></div>${socialSection(s)}${heroAuditSection(s)}<div class="fact-box"><h4>アクセス</h4><p>${s.address}</p><a class="official-link" href="${s.official_url}" target="_blank" rel="noopener">公式サイトを見る →</a></div></div>`;dialog.showModal();requestAnimationFrame(()=>{processInstagramEmbeds();enhancePlacePhotos(dialog);loadHeroAudit(s);});}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('kibun-favorites',JSON.stringify([...favorites]));$('favoriteCount').textContent=favorites.size;if(lastResult&&!resultsSection.hidden){const y=scrollY;resultsGrid.innerHTML=lastResult.recommendations.map(resultCard).join('');wireResultActions();scrollTo(0,y);}}
$('clearVibes').addEventListener('click',()=>{selectedVibes=[];renderVibes()});recommendBtn.addEventListener('click',renderRecommendations);$('locationBtn').addEventListener('click',useCurrentLocation);$('editBtn').addEventListener('click',()=>document.querySelector('.hero').scrollIntoView({behavior:'smooth'}));$('dialogClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});$('favoritesBtn').addEventListener('click',()=>alert(favorites.size?`お気に入り ${favorites.size}件\n${[...favorites].map(id=>'・'+findSpot(id)?.name).join('\n')}`:'まだお気に入りはありません。'));document.querySelectorAll('.collection-card').forEach(btn=>btn.addEventListener('click',()=>{selectedVibes=btn.dataset.vibes.split(',').slice(0,3);renderVibes();document.querySelector('.hero').scrollIntoView({behavior:'smooth'});}));$('favoriteCount').textContent=favorites.size;renderAudience();updateAudienceUi();renderVibes();renderTrending();installHeroAuditDock();