window.KIBUN_PERFORMANCES = {
  "metadata": {
    "version": "0.20.15.0",
    "checked_at": "2026-09-11",
    "source_policy": "Official venue and organizer pages only.",
    "display_policy": "Events are hidden after end_date. Start times, ticket inventory and cancellations must be rechecked on the official page.",
    "genres": {
      "ballet": "バレエ",
      "opera": "オペラ",
      "musical": "ミュージカル",
      "theater": "演劇",
      "kabuki": "歌舞伎",
      "noh_kyogen": "能・狂言",
      "classical": "クラシック",
      "dance": "ダンス",
      "live": "ライブ",
      "family": "親子向け"
    }
  },
  "performances": [
    {
      "performance_id": "perf_nntt_turco",
      "venue_spot_id": "spot_479",
      "title": "オペラ「イタリアのトルコ人」",
      "title_en": "Il turco in Italia",
      "genre": "opera",
      "start_date": "2026-10-02",
      "end_date": "2026-10-12",
      "schedule_summary": "新国立劇場 主催オペラ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nntt.jac.go.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nntt_citylights",
      "venue_spot_id": "spot_479",
      "title": "バレエ「街の灯」",
      "title_en": "The City Lights",
      "genre": "ballet",
      "start_date": "2026-10-23",
      "end_date": "2026-11-01",
      "schedule_summary": "バレエ＆ダンス",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nntt.jac.go.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nntt_master",
      "venue_spot_id": "spot_479",
      "title": "演劇「巨匠とマルガリータ」",
      "title_en": "The Master and Margarita",
      "genre": "theater",
      "start_date": "2026-11-07",
      "end_date": "2026-11-23",
      "schedule_summary": "演劇",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nntt.jac.go.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nntt_grimes",
      "venue_spot_id": "spot_479",
      "title": "オペラ「ピーター・グライムズ」",
      "title_en": "Peter Grimes",
      "genre": "opera",
      "start_date": "2026-11-23",
      "end_date": "2026-12-05",
      "schedule_summary": "新国立劇場 主催オペラ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nntt.jac.go.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nntt_dttf",
      "venue_spot_id": "spot_479",
      "title": "DANCE to the Future 2026",
      "title_en": "DANCE to the Future 2026",
      "genre": "dance",
      "start_date": "2026-11-27",
      "end_date": "2026-11-29",
      "schedule_summary": "ダンス",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nntt.jac.go.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nntt_nutcracker",
      "venue_spot_id": "spot_479",
      "title": "バレエ「くるみ割り人形」",
      "title_en": "The Nutcracker",
      "genre": "ballet",
      "start_date": "2026-12-18",
      "end_date": "2027-01-03",
      "schedule_summary": "年末年始のバレエ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nntt.jac.go.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kaat_jungle",
      "venue_spot_id": "spot_245",
      "title": "『ジャングル』",
      "title_en": "The Jungle",
      "genre": "theater",
      "start_date": "2026-10-10",
      "end_date": "2026-11-01",
      "schedule_summary": "KAAT×阿佐ヶ谷スパイダース",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kaat.jp/news_detail/2981",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kaat_kaerushoten",
      "venue_spot_id": "spot_245",
      "title": "『蛙昇天』",
      "title_en": "Kaeru Shoten",
      "genre": "theater",
      "start_date": "2026-10-24",
      "end_date": "2026-11-08",
      "schedule_summary": "KAATプロデュース",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kaat.jp/news_detail/2981",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kaat_closeup",
      "venue_spot_id": "spot_245",
      "title": "DANCE SERIES『Close Up -クローズ・アップ-』",
      "title_en": "Close Up",
      "genre": "dance",
      "start_date": "2026-11-28",
      "end_date": "2026-11-29",
      "schedule_summary": "ダンスと古楽器アンサンブル",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kaat.jp/news_detail/2981",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kaat_jazzdaimyo",
      "venue_spot_id": "spot_245",
      "title": "『ジャズ大名』",
      "title_en": "Jazz Daimyo",
      "genre": "theater",
      "start_date": "2026-12-19",
      "end_date": "2026-12-29",
      "schedule_summary": "KAATプロデュース",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kaat.jp/news_detail/2981",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_geigeki_lear",
      "venue_spot_id": "spot_480",
      "title": "『リア王 -KING LEAR-』",
      "title_en": "KING LEAR",
      "genre": "theater",
      "start_date": "2026-09-21",
      "end_date": "2026-10-04",
      "schedule_summary": "演劇",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.geigeki.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_geigeki_meteor",
      "venue_spot_id": "spot_480",
      "title": "舞台芸術祭「秋の隕石2026東京」",
      "title_en": "Autumn Meteor 2026 Tokyo",
      "genre": "theater",
      "start_date": "2026-10-09",
      "end_date": "2026-11-03",
      "schedule_summary": "舞台芸術祭",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.geigeki.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": [
        "festival"
      ]
    },
    {
      "performance_id": "perf_geigeki_trotter",
      "venue_spot_id": "spot_480",
      "title": "トーマス・トロッター オルガン・リサイタル",
      "title_en": "Thomas Trotter Organ Recital",
      "genre": "classical",
      "start_date": "2026-10-09",
      "end_date": "2026-10-09",
      "schedule_summary": "コンサートホールのパイプオルガン",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.geigeki.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_geigeki_silence",
      "venue_spot_id": "spot_480",
      "title": "『静寂のガツンとした一撃』",
      "title_en": "A Powerful Blow of Silence",
      "genre": "dance",
      "start_date": "2026-10-25",
      "end_date": "2026-10-25",
      "schedule_summary": "約30分予定",
      "duration_minutes": 30,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.geigeki.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_geigeki_lunchorgan",
      "venue_spot_id": "spot_480",
      "title": "ランチタイム・パイプオルガンコンサート",
      "title_en": "Lunchtime Pipe Organ Concert",
      "genre": "classical",
      "start_date": "2026-11-05",
      "end_date": "2026-11-05",
      "schedule_summary": "昼の短時間コンサート",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.geigeki.jp/performance/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_orb_nine",
      "venue_spot_id": "spot_481",
      "title": "宝塚歌劇 月組公演『NINE』",
      "title_en": "Takarazuka Moon Troupe: NINE",
      "genre": "musical",
      "start_date": "2026-09-10",
      "end_date": "2026-09-27",
      "schedule_summary": "渋谷ヒカリエ・東急シアターオーブ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://theatre-orb.com/lineup/calendar/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_orb_saigon",
      "venue_spot_id": "spot_481",
      "title": "ミュージカル『ミス・サイゴン』",
      "title_en": "Miss Saigon",
      "genre": "musical",
      "start_date": "2026-10-16",
      "end_date": "2026-11-30",
      "schedule_summary": "プレビュー公演を含む",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://theatre-orb.com/lineup/calendar/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nissay_funnygirl",
      "venue_spot_id": "spot_482",
      "title": "『ファニー・ガール』",
      "title_en": "Funny Girl",
      "genre": "musical",
      "start_date": "2026-09-08",
      "end_date": "2026-09-29",
      "schedule_summary": "ミュージカル",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nissaytheatre.or.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nissay_fanfare",
      "venue_spot_id": "spot_482",
      "title": "KURUMU OKAMIYA 1st Concert『The Fanfare』",
      "title_en": "KURUMU OKAMIYA 1st Concert: The Fanfare",
      "genre": "live",
      "start_date": "2026-10-03",
      "end_date": "2026-10-05",
      "schedule_summary": "コンサート",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nissaytheatre.or.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nissay_101",
      "venue_spot_id": "spot_482",
      "title": "ミュージカル『101ダルメシアンズ』",
      "title_en": "101 Dalmatians",
      "genre": "musical",
      "start_date": "2026-10-13",
      "end_date": "2026-10-29",
      "schedule_summary": "ミュージカル",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nissaytheatre.or.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nissay_dongiovanni",
      "venue_spot_id": "spot_482",
      "title": "オペラ『ドン・ジョヴァンニ』",
      "title_en": "Don Giovanni",
      "genre": "opera",
      "start_date": "2026-11-14",
      "end_date": "2026-11-15",
      "schedule_summary": "日生劇場主催オペラ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nissaytheatre.or.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nissay_yuzuru",
      "venue_spot_id": "spot_482",
      "title": "オペラ『夕鶴』",
      "title_en": "Yuzuru",
      "genre": "opera",
      "start_date": "2026-11-27",
      "end_date": "2026-11-29",
      "schedule_summary": "日本オペラ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nissaytheatre.or.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_nissay_cage",
      "venue_spot_id": "spot_482",
      "title": "『ラ・カージュ・オ・フォール』",
      "title_en": "La Cage aux Folles",
      "genre": "musical",
      "start_date": "2026-12-09",
      "end_date": "2026-12-29",
      "schedule_summary": "ミュージカル",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.nissaytheatre.or.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_takarazuka_rrr",
      "venue_spot_id": "spot_483",
      "title": "星組『RRR × TAKA”R”AZUKA ～√Rama～』",
      "title_en": "Star Troupe: RRR × TAKA“R”AZUKA",
      "genre": "musical",
      "start_date": "2026-10-31",
      "end_date": "2026-12-13",
      "schedule_summary": "東京宝塚劇場公演",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://kageki.hankyu.co.jp/revue/2026/rrr/ticket_tokyo.html",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_noh_kinno",
      "venue_spot_id": "spot_484",
      "title": "10月定例公演「禁野・熊坂」",
      "title_en": "October Regular Performance: Kinno / Kumasaka",
      "genre": "noh_kyogen",
      "start_date": "2026-10-07",
      "end_date": "2026-10-07",
      "schedule_summary": "13:00開演",
      "duration_minutes": null,
      "age_note": null,
      "language_note": "日本語・英語字幕あり",
      "childcare": null,
      "official_url": "https://www.ntj.jac.go.jp/nou/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_noh_naruko",
      "venue_spot_id": "spot_484",
      "title": "10月普及公演「鳴子・夕顔」",
      "title_en": "October Introductory Performance: Naruko / Yugao",
      "genre": "noh_kyogen",
      "start_date": "2026-10-10",
      "end_date": "2026-10-10",
      "schedule_summary": "普及公演",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.ntj.jac.go.jp/nou/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_noh_narayama",
      "venue_spot_id": "spot_484",
      "title": "10月企画公演「楢山節考・鐵門」",
      "title_en": "October Special Performance: Narayama Bushiko / Tetsumon",
      "genre": "noh_kyogen",
      "start_date": "2026-10-15",
      "end_date": "2026-10-15",
      "schedule_summary": "18:30開演",
      "duration_minutes": null,
      "age_note": null,
      "language_note": "日本語・英語字幕あり",
      "childcare": null,
      "official_url": "https://www.ntj.jac.go.jp/nou/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_noh_discover",
      "venue_spot_id": "spot_484",
      "title": "外国人のための能楽鑑賞教室 Discover Noh & Kyogen",
      "title_en": "Discover Noh & Kyogen",
      "genre": "noh_kyogen",
      "start_date": "2026-10-30",
      "end_date": "2026-10-30",
      "schedule_summary": "「二人袴／安達原」",
      "duration_minutes": null,
      "age_note": null,
      "language_note": "外国人向け鑑賞教室",
      "childcare": null,
      "official_url": "https://www.ntj.jac.go.jp/nou/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kabuki_sep",
      "venue_spot_id": "spot_242",
      "title": "秀山祭九月大歌舞伎",
      "title_en": "Shuzansai September Grand Kabuki",
      "genre": "kabuki",
      "start_date": "2026-09-02",
      "end_date": "2026-09-26",
      "schedule_summary": "歌舞伎座",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kabuki-bito.jp/theaters/kabukiza/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kabuki_oct",
      "venue_spot_id": "spot_242",
      "title": "錦秋十月大歌舞伎",
      "title_en": "October Grand Kabuki",
      "genre": "kabuki",
      "start_date": "2026-10-02",
      "end_date": "2026-10-20",
      "schedule_summary": "歌舞伎座",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": true,
      "official_url": "https://www.kabuki-bito.jp/theaters/kabukiza/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kabuki_nov",
      "venue_spot_id": "spot_242",
      "title": "吉例顔見世大歌舞伎",
      "title_en": "November Kaomise Grand Kabuki",
      "genre": "kabuki",
      "start_date": "2026-11-01",
      "end_date": "2026-11-25",
      "schedule_summary": "歌舞伎座",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kabuki-bito.jp/theaters/kabukiza/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_kabuki_dec",
      "venue_spot_id": "spot_242",
      "title": "十二月大歌舞伎",
      "title_en": "December Grand Kabuki",
      "genre": "kabuki",
      "start_date": "2026-12-02",
      "end_date": "2026-12-25",
      "schedule_summary": "歌舞伎座",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kabuki-bito.jp/theaters/kabukiza/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_enbujo_lear",
      "venue_spot_id": "spot_244",
      "title": "『リア王』",
      "title_en": "King Lear",
      "genre": "theater",
      "start_date": "2026-09-06",
      "end_date": "2026-09-22",
      "schedule_summary": "新橋演舞場",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.shochiku.co.jp/play/theater/enbujyo/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_enbujo_impact",
      "venue_spot_id": "spot_244",
      "title": "『IMPACT26』",
      "title_en": "IMPACT26",
      "genre": "theater",
      "start_date": "2026-10-02",
      "end_date": "2026-10-28",
      "schedule_summary": "新橋演舞場",
      "duration_minutes": null,
      "age_note": "未就学児入場不可",
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.shochiku.co.jp/play/theater/enbujyo/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_enbujo_dokuro",
      "venue_spot_id": "spot_244",
      "title": "劇団☆新感線『髑髏城の七人 LAST STAND』",
      "title_en": "Seven Souls in the Skull Castle: LAST STAND",
      "genre": "theater",
      "start_date": "2026-11-14",
      "end_date": "2026-12-25",
      "schedule_summary": "新橋演舞場",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.shochiku.co.jp/play/theater/enbujyo/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_shiki_frozen",
      "venue_spot_id": "spot_243",
      "title": "ミュージカル『アナと雪の女王』",
      "title_en": "Disney FROZEN",
      "genre": "musical",
      "start_date": "2026-04-01",
      "end_date": "2027-01-17",
      "schedule_summary": "JR東日本四季劇場［春］",
      "duration_minutes": null,
      "age_note": "3歳未満入場不可。3歳以上はチケット必要。",
      "language_note": null,
      "childcare": true,
      "official_url": "https://www.shiki.jp/theatres/4023/",
      "checked_at": "2026-09-11",
      "tags": [
        "family"
      ]
    },
    {
      "performance_id": "perf_shiki_lionking",
      "venue_spot_id": "spot_489",
      "title": "ミュージカル『ライオンキング』",
      "title_en": "Disney THE LION KING",
      "genre": "musical",
      "start_date": "2026-07-01",
      "end_date": "2026-12-31",
      "schedule_summary": "有明四季劇場",
      "duration_minutes": 160,
      "age_note": "3歳未満入場不可。3歳以上はチケット必要。",
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.shiki.jp/stage_schedule/?aj=0&ggc=4026&rid=0057",
      "checked_at": "2026-09-11",
      "tags": [
        "family"
      ]
    },
    {
      "performance_id": "perf_mm_organ_sep",
      "venue_spot_id": "spot_485",
      "title": "オルガン・1アワーコンサート",
      "title_en": "Organ 1-Hour Concert",
      "genre": "classical",
      "start_date": "2026-09-18",
      "end_date": "2026-09-18",
      "schedule_summary": "約1時間で楽しむパイプオルガン",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-minatomiraihall.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_mm_dollar",
      "venue_spot_id": "spot_485",
      "title": "オルガン・1ドルコンサート",
      "title_en": "Organ 1-Dollar Concert",
      "genre": "classical",
      "start_date": "2026-10-21",
      "end_date": "2026-10-21",
      "schedule_summary": "気軽に立ち寄れるオルガン公演",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-minatomiraihall.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_mm_strings",
      "venue_spot_id": "spot_485",
      "title": "Salon de Strings vol.6",
      "title_en": "Salon de Strings vol.6",
      "genre": "classical",
      "start_date": "2026-10-21",
      "end_date": "2026-10-21",
      "schedule_summary": "室内楽",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-minatomiraihall.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_mm_piano",
      "venue_spot_id": "spot_485",
      "title": "第44回 横浜市招待国際ピアノ演奏会",
      "title_en": "44th Yokohama International Piano Concert",
      "genre": "classical",
      "start_date": "2026-11-07",
      "end_date": "2026-11-07",
      "schedule_summary": "ピアノ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-minatomiraihall.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_mm_animals",
      "venue_spot_id": "spot_485",
      "title": "親子で楽しむ「音と光の動物園」",
      "title_en": "Sound and Light Zoo for Families",
      "genre": "family",
      "start_date": "2026-12-06",
      "end_date": "2026-12-06",
      "schedule_summary": "親子で楽しむ発達支援ワークショップ＆コンサート",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-minatomiraihall.jp/",
      "checked_at": "2026-09-11",
      "tags": [
        "family"
      ]
    },
    {
      "performance_id": "perf_mm_xmas",
      "venue_spot_id": "spot_485",
      "title": "クリスマス・パイプオルガン・コンサート2026",
      "title_en": "Christmas Pipe Organ Concert 2026",
      "genre": "classical",
      "start_date": "2026-12-22",
      "end_date": "2026-12-22",
      "schedule_summary": "クリスマスのオルガン公演",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-minatomiraihall.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_mm_ishidagumi",
      "venue_spot_id": "spot_485",
      "title": "石田組 年末感謝祭2026",
      "title_en": "Ishida-gumi Year-End Festival 2026",
      "genre": "classical",
      "start_date": "2026-12-30",
      "end_date": "2026-12-31",
      "schedule_summary": "年末公演",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-minatomiraihall.jp/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ongakudo_cello",
      "venue_spot_id": "spot_486",
      "title": "《究極チェロ・クァルテット》",
      "title_en": "Ultimate Cello Quartet",
      "genre": "classical",
      "start_date": "2026-09-13",
      "end_date": "2026-09-13",
      "schedule_summary": null,
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kanagawa-ongakudo.com/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ongakudo_opera",
      "venue_spot_id": "spot_486",
      "title": "第35回神奈川オペラフェスティバル’26 オペラ・ガラコンサート",
      "title_en": "Kanagawa Opera Festival 2026: Opera Gala",
      "genre": "opera",
      "start_date": "2026-09-20",
      "end_date": "2026-09-20",
      "schedule_summary": null,
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kanagawa-ongakudo.com/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ongakudo_miura",
      "venue_spot_id": "spot_486",
      "title": "三浦謙司: In Portrait",
      "title_en": "Kenji Miura: In Portrait",
      "genre": "classical",
      "start_date": "2026-09-24",
      "end_date": "2026-09-24",
      "schedule_summary": "ピアノ",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kanagawa-ongakudo.com/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ongakudo_feast",
      "venue_spot_id": "spot_486",
      "title": "《至高の響宴》",
      "title_en": "A Supreme Musical Feast",
      "genre": "classical",
      "start_date": "2026-10-12",
      "end_date": "2026-10-12",
      "schedule_summary": null,
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kanagawa-ongakudo.com/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ongakudo_biondi",
      "venue_spot_id": "spot_486",
      "title": "ファビオ・ビオンディ／エウローパ・ガランテ「四季」とイタリアの宝石",
      "title_en": "Fabio Biondi & Europa Galante",
      "genre": "classical",
      "start_date": "2026-11-06",
      "end_date": "2026-11-06",
      "schedule_summary": "「四季」とイタリアの宝石",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kanagawa-ongakudo.com/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ongakudo_kids",
      "venue_spot_id": "spot_486",
      "title": "子どものための音楽堂 せかいはともだち！",
      "title_en": "Music Hall for Children: The World Is Our Friend!",
      "genre": "family",
      "start_date": "2027-01-16",
      "end_date": "2027-01-16",
      "schedule_summary": null,
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.kanagawa-ongakudo.com/",
      "checked_at": "2026-09-11",
      "tags": [
        "family"
      ]
    },
    {
      "performance_id": "perf_ynoh_71",
      "venue_spot_id": "spot_487",
      "title": "第71回 横浜能",
      "title_en": "71st Yokohama Noh",
      "genre": "noh_kyogen",
      "start_date": "2026-09-13",
      "end_date": "2026-09-13",
      "schedule_summary": null,
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-nohgakudou.org/schedule/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ynoh_30sep",
      "venue_spot_id": "spot_487",
      "title": "開館30周年記念 特別公演",
      "title_en": "30th Anniversary Special Performance",
      "genre": "noh_kyogen",
      "start_date": "2026-09-26",
      "end_date": "2026-09-26",
      "schedule_summary": null,
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-nohgakudou.org/schedule/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ynoh_kyogen_oct",
      "venue_spot_id": "spot_487",
      "title": "横浜狂言堂",
      "title_en": "Yokohama Kyogen-do",
      "genre": "noh_kyogen",
      "start_date": "2026-10-11",
      "end_date": "2026-10-11",
      "schedule_summary": "狂言2曲＋解説",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-nohgakudou.org/schedule/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ynoh_30oct",
      "venue_spot_id": "spot_487",
      "title": "開館30周年記念 特別公演",
      "title_en": "30th Anniversary Special Performance",
      "genre": "noh_kyogen",
      "start_date": "2026-10-24",
      "end_date": "2026-10-24",
      "schedule_summary": null,
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-nohgakudou.org/schedule/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ynoh_kyogen_nov",
      "venue_spot_id": "spot_487",
      "title": "横浜狂言堂",
      "title_en": "Yokohama Kyogen-do",
      "genre": "noh_kyogen",
      "start_date": "2026-11-08",
      "end_date": "2026-11-08",
      "schedule_summary": "狂言＋解説",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-nohgakudou.org/schedule/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ynoh_kyogen_dec",
      "venue_spot_id": "spot_487",
      "title": "横浜狂言堂",
      "title_en": "Yokohama Kyogen-do",
      "genre": "noh_kyogen",
      "start_date": "2026-12-13",
      "end_date": "2026-12-13",
      "schedule_summary": "狂言＋解説",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-nohgakudou.org/schedule/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_ynoh_sleep",
      "venue_spot_id": "spot_487",
      "title": "眠くならずに楽しめる能の名曲",
      "title_en": "A Noh Masterpiece You Can Enjoy Without Dozing Off",
      "genre": "noh_kyogen",
      "start_date": "2026-12-20",
      "end_date": "2026-12-20",
      "schedule_summary": "初めての能にも選びやすい企画",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://yokohama-nohgakudou.org/schedule/",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_mayumura",
      "venue_spot_id": "spot_488",
      "title": "眉村ちあき",
      "title_en": "Chiaki Mayumura",
      "genre": "live",
      "start_date": "2026-09-12",
      "end_date": "2026-09-12",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_travellers",
      "venue_spot_id": "spot_488",
      "title": "TRAVELLERS",
      "title_en": "TRAVELLERS",
      "genre": "live",
      "start_date": "2026-09-14",
      "end_date": "2026-09-14",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_dezolve",
      "venue_spot_id": "spot_488",
      "title": "DEZOLVE",
      "title_en": "DEZOLVE",
      "genre": "live",
      "start_date": "2026-09-16",
      "end_date": "2026-09-16",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_yonekura",
      "venue_spot_id": "spot_488",
      "title": "米倉利紀",
      "title_en": "Toshinori Yonekura",
      "genre": "live",
      "start_date": "2026-09-17",
      "end_date": "2026-09-17",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_honda",
      "venue_spot_id": "spot_488",
      "title": "本田雅人BAND",
      "title_en": "Masato Honda BAND",
      "genre": "live",
      "start_date": "2026-09-20",
      "end_date": "2026-09-20",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_kawabata",
      "venue_spot_id": "spot_488",
      "title": "川畑 要",
      "title_en": "Kaname Kawabata",
      "genre": "live",
      "start_date": "2026-09-21",
      "end_date": "2026-09-21",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_lagheads",
      "venue_spot_id": "spot_488",
      "title": "LAGHEADS",
      "title_en": "LAGHEADS",
      "genre": "live",
      "start_date": "2026-09-26",
      "end_date": "2026-09-26",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    },
    {
      "performance_id": "perf_bill_aran",
      "venue_spot_id": "spot_488",
      "title": "安蘭けい",
      "title_en": "Kei Aran",
      "genre": "live",
      "start_date": "2026-09-27",
      "end_date": "2026-09-27",
      "schedule_summary": "Billboard Live YOKOHAMA",
      "duration_minutes": null,
      "age_note": null,
      "language_note": null,
      "childcare": null,
      "official_url": "https://www.billboard-live.com/yokohama/schedules",
      "checked_at": "2026-09-11",
      "tags": []
    }
  ]
};
