(function(root,factory){
  if(typeof module==='object'&&module.exports)module.exports=factory(require('./recommender.js'));
  else root.KibunPlans=factory(root.OdekakeRecommender);
})(typeof globalThis!=='undefined'?globalThis:this,function(Recommender){
  const {baseScores,hardFilterReason}=Recommender||{};
  const clamp=(x,lo=0,hi=100)=>Math.max(lo,Math.min(hi,x));
  function spotMap(seed){return new Map((seed.spots||[]).map(s=>[s.spot_id,s]));}
  function areaKey(s){const text=`${s.city||''} ${s.address||''}`;if(/横浜市/.test(text))return'横浜市';if(/川崎市/.test(text))return'川崎市';if(/箱根町/.test(text))return'箱根町';if(/鎌倉市/.test(text))return'鎌倉市';if(/藤沢市/.test(text))return'藤沢市';if(/逗子市/.test(text))return'逗子市';if(/三浦市/.test(text))return'三浦市';if(/横須賀市/.test(text))return'横須賀市';if(/鴨川市/.test(text))return'鴨川市';if(/木更津市/.test(text))return'木更津市';if(/浦安市/.test(text))return'浦安市';if(/伊東市/.test(text))return'伊東市';if(/東伊豆町/.test(text))return'東伊豆町';return s.routing?.municipality||s.city||s.prefecture||'';}
  function groupKey(s){return s.recommendation_group||s.spot_id;}
  function categoryKind(s){const p=String(s.category_primary||'').toLowerCase(),x=[s.category_primary,...(s.categories||[])].join('|').toLowerCase();if(s.overnight||/hotel|stay|ryokan|resort/.test(p))return'stay';if(/creative|workshop|experience|craft|pottery|glass|fragrance|washi|interactive|music/.test(p))return'experience';if(/food|cafe|restaurant|market|dining/.test(p))return'food';if(/relax|spa|onsen|bath/.test(p))return'relax';if(/culture|museum|gallery|library|temple|stage|theater|art|architecture/.test(p))return'culture';if(/theme|zoo|aquarium|pool|play|amusement/.test(p))return'activity';if(/park|nature|garden|waterside|beach/.test(p))return'nature';if(/shopping|mall/.test(p))return'shopping';if(/workshop|experience|craft|pottery|glass|fragrance|washi/.test(x))return'experience';if(/museum|gallery|library|temple|stage|theater|culture/.test(x))return'culture';if(/food|cafe|restaurant|market|dining/.test(x))return'food';if(/shopping|mall/.test(x))return'shopping';if(/park|nature|garden|waterside|beach/.test(x))return'nature';return'other';}
  function complementScore(a,b){const ka=categoryKind(a),kb=categoryKind(b);if(ka===kb)return 30;if((ka==='activity'||ka==='culture'||ka==='experience'||ka==='nature')&&kb==='food')return 100;if(ka==='food'&&['culture','experience','nature','shopping'].includes(kb))return 92;if(ka==='activity'&&kb==='relax')return 88;if(ka==='culture'&&['food','nature','shopping'].includes(kb))return 86;if(ka==='experience'&&['food','shopping','nature'].includes(kb))return 86;if(ka==='nature'&&['food','relax'].includes(kb))return 84;if(ka==='shopping'&&kb==='food')return 90;if(kb==='stay')return 94;return 65;}
  function durationLabel(minutes,type){if(type==='overnight')return'1泊プラン';if(minutes<=120)return'1〜2時間';if(minutes<=240)return'半日くらい';if(minutes<=390)return'たっぷり半日';return'1日プラン';}
  function requestedDurationLabel(minutes){return durationLabel(Number(minutes||180),'day');}
  function minCoverageMinutes(displayMinutes){const m=Number(displayMinutes||180);if(m<=120)return Math.max(45,m*.5);if(m<=240)return m*.62;if(m<=390)return m*.60;return m*.56;}
  function shouldStaySingle(s,displayMinutes){const stay=Number(s.stay_minutes_seed||120);if(s.overnight)return false;if(displayMinutes<=120)return true;if(stay>=Math.max(105,displayMinutes*.62))return true;if(stay>=150&&displayMinutes<=240)return true;return false;}
  function eligible(s,ctx,allowOvernight){if(!s)return false;const c={...ctx,allowOvernight,includeBrowseOnly:false};return typeof hardFilterReason==='function'?!hardFilterReason(s,c):s.recommendation_mode!=='browse_only'&&(allowOvernight||!s.overnight);}
  function rankedCompanions(seed,primary,ctx,remaining,used,opts={}){if(remaining<45)return[];const primaryArea=areaKey(primary);return (seed.spots||[]).filter(s=>s.spot_id!==primary.spot_id&&!used.has(s.spot_id)&&groupKey(s)!==groupKey(primary)&&areaKey(s)===primaryArea&&eligible(s,ctx,!!opts.allowOvernight)&&Number(s.stay_minutes_seed||120)<=Math.max(60,remaining+25)&&Number(s.stay_minutes_seed||120)>=35).map(s=>{const sc=typeof baseScores==='function'?baseScores(s,{...ctx,allowOvernight:!!opts.allowOvernight,availableMinutes:remaining}):{overall:70};const comp=complementScore(primary,s);const shortPenalty=Math.max(0,Number(s.stay_minutes_seed||120)-remaining)*.3;return{s,score:.62*Number(sc.overall||70)+.38*comp-shortPenalty};}).sort((a,b)=>b.score-a.score);
  }
  function naturalSingleTitle(s,displayMinutes){if(s.editorial?.title)return s.editorial.title;const k=categoryKind(s),d=requestedDurationLabel(displayMinutes);if(k==='activity')return`${s.name}を主役に、今日は思いきり楽しむ。`;if(k==='culture')return`${s.name}で、気になるものをゆっくり見る。`;if(k==='experience')return`${s.name}で、いつもと違う体験をひとつ。`;if(k==='nature')return`${s.name}で、のんびり過ごす${d==='1〜2時間'?'時間':'半日'}。`;if(k==='relax')return`${s.name}で、予定を詰めない時間を。`;if(k==='food')return`${s.name}を目的地に、おいしい時間を。`;if(k==='shopping')return`${s.name}を、気ままに見て歩く。`;if(k==='stay')return`${s.name}で、今日はそのまま泊まる。`;return`${s.name}を主役に、今日はここへ。`;}
  function firstSentence(text){const t=String(text||'').trim();if(!t)return'';const m=t.match(/^(.+?[。！？])/);return(m?m[1]:t).trim();}
  function naturalSingleLead(s,displayMinutes){if(s.editorial?.lead)return s.editorial.lead;const fact=firstSentence(s.public_copy),d=requestedDurationLabel(displayMinutes),k=categoryKind(s);const tail=d==='1〜2時間'?'短い時間でも、ここを目的地にする過ごし方。':`${d}を使って、予定を詰め込みすぎずここを中心に。`;if(fact)return`${fact}${tail}`;if(k==='experience')return`見るだけで終わらず、体験そのものを楽しむ。${tail}`;if(k==='culture')return`気になったものの前で立ち止まりながら、急がず見て回る。${tail}`;return tail;}
  function comboTitle(a,b,type,displayMinutes){if(type==='overnight')return`${a.name}を楽しんだあと、${b.name}に泊まる。`;const kb=categoryKind(b),d=requestedDurationLabel(displayMinutes);if(kb==='food')return`${a.name}を楽しんで、${b.name}でひと休み。`;if(categoryKind(a)==='food')return`${a.name}から始める、${areaKey(a)}の${d==='1〜2時間'?'寄り道':'半日'}。`;return`${a.name}と${b.name}で過ごす、${areaKey(a)}の${d==='1〜2時間'?'寄り道':'半日'}。`;}
  function comboLead(a,b,type){if(type==='overnight')return`昼は${a.name}へ。そのあとは${b.name}へ移って、夜まで急がず過ごす。`;return`まず${a.name}へ。そのあと${b.name}へ。移動を詰め込みすぎず、2つの場所をゆるくつなぐプラン。`;}
  function coverageMinutes(spots){return spots.reduce((sum,s)=>sum+Number(s?.stay_minutes_seed||0),0)+(spots.length>1?30:0);}
  function coverageOk(spots,displayMinutes){if(Number(displayMinutes||180)<=120)return true;return coverageMinutes(spots)>=minCoverageMinutes(displayMinutes);}
  function buildOne(seed,r,ctx,used,allPrimaryIds,opts){const map=spotMap(seed),primary=map.get(r.spot_id);if(!primary)return null;const displayMinutes=Number(opts.displayMinutes||ctx.availableMinutes||180);const requestedLabel=requestedDurationLabel(displayMinutes);const base={plan_id:`plan_${r.slot||primary.spot_id}`,slot:r.slot,slot_label:r.slot_label,score:Number(r.scores?.overall||70),travel_minutes:r.travel_minutes??null,why:r.why||[],primary_spot_id:primary.spot_id,requested_minutes:displayMinutes};
    if(primary.overnight){const dayCandidates=rankedCompanions(seed,primary,{...ctx,allowOvernight:false},300,new Set([...used,...allPrimaryIds]),{allowOvernight:false});const day=dayCandidates[0]?.s;if(day){used.add(day.spot_id);return{...base,type:'overnight',duration_label:'1泊プラン',estimated_minutes:null,title:comboTitle(day,primary,'overnight',displayMinutes),lead:comboLead(day,primary,'overnight'),spot_ids:[day.spot_id,primary.spot_id],steps:[{spot_id:day.spot_id,role:'DAY',label:'昼の主役'},{spot_id:primary.spot_id,role:'STAY',label:'泊まる'}]};}return{...base,type:'overnight',duration_label:'1泊プラン',estimated_minutes:null,title:naturalSingleTitle(primary,displayMinutes),lead:naturalSingleLead(primary,displayMinutes),spot_ids:[primary.spot_id],steps:[{spot_id:primary.spot_id,role:'STAY',label:'泊まる'}]};}
    if(shouldStaySingle(primary,displayMinutes)){const mins=coverageMinutes([primary]);return{...base,type:'single',duration_label:requestedLabel,estimated_minutes:mins,title:naturalSingleTitle(primary,displayMinutes),lead:naturalSingleLead(primary,displayMinutes),spot_ids:[primary.spot_id],steps:[{spot_id:primary.spot_id,role:'MAIN',label:'今日の主役'}]};}
    const remain=Math.max(0,displayMinutes-Number(primary.stay_minutes_seed||120)-30);const blocked=new Set([...used,...allPrimaryIds]);const companions=rankedCompanions(seed,primary,{...ctx,allowOvernight:false},remain,blocked,{allowOvernight:false});let companion=companions.map(x=>x.s).find(s=>coverageOk([primary,s],displayMinutes))||null;
    if(!companion&&ctx.allowOvernight){const hotels=rankedCompanions(seed,primary,{...ctx,allowOvernight:true},720,blocked,{allowOvernight:true}).filter(x=>x.s.overnight);companion=hotels[0]?.s||null;if(companion){used.add(companion.spot_id);return{...base,type:'overnight',duration_label:'1泊プラン',estimated_minutes:null,title:comboTitle(primary,companion,'overnight',displayMinutes),lead:comboLead(primary,companion,'overnight'),spot_ids:[primary.spot_id,companion.spot_id],steps:[{spot_id:primary.spot_id,role:'DAY',label:'昼の主役'},{spot_id:companion.spot_id,role:'STAY',label:'泊まる'}]};}}
    if(companion){used.add(companion.spot_id);const total=coverageMinutes([primary,companion]);return{...base,type:'combo',duration_label:requestedLabel,estimated_minutes:total,title:comboTitle(primary,companion,'combo',displayMinutes),lead:comboLead(primary,companion,'combo'),spot_ids:[primary.spot_id,companion.spot_id],steps:[{spot_id:primary.spot_id,role:'MAIN',label:'まずここ'},{spot_id:companion.spot_id,role:'PLUS',label:'もうひとつ'}]};}
    if(displayMinutes<=120){const mins=coverageMinutes([primary]);return{...base,type:'single',duration_label:requestedLabel,estimated_minutes:mins,title:naturalSingleTitle(primary,displayMinutes),lead:naturalSingleLead(primary,displayMinutes),spot_ids:[primary.spot_id],steps:[{spot_id:primary.spot_id,role:'MAIN',label:'今日の主役'}]};}
    return null;
  }
  function fallbackCandidates(seed,ctx,displayMinutes,blockedIds,blockedGroups){return(seed.spots||[]).filter(s=>!blockedIds.has(s.spot_id)&&!blockedGroups.has(groupKey(s))&&eligible(s,{...ctx,availableMinutes:displayMinutes},!!ctx.allowOvernight)).map(s=>{const scores=typeof baseScores==='function'?baseScores(s,{...ctx,availableMinutes:displayMinutes}):{overall:70};return{spot_id:s.spot_id,name:s.name,scores,travel_minutes:ctx.travelMinutesBySpot?.[s.spot_id]??null,why:[]};}).sort((a,b)=>Number(b.scores?.overall||0)-Number(a.scores?.overall||0));}
  function buildPlans(seed,recommendationResult,ctx={},opts={}){const recs=recommendationResult?.recommendations||[],displayMinutes=Number(opts.displayMinutes||ctx.availableMinutes||180),usedCompanions=new Set(),usedPrimaryIds=new Set(),usedGroups=new Set(),originalPrimaryIds=new Set(recs.map(r=>r.spot_id)),plans=[];for(const r of recs){let p=buildOne(seed,r,ctx,usedCompanions,originalPrimaryIds,opts);let chosenId=r.spot_id;if(!p){const slot=r.slot,slot_label=r.slot_label;const candidates=fallbackCandidates(seed,ctx,displayMinutes,new Set([...usedPrimaryIds,...usedCompanions,...originalPrimaryIds]),usedGroups);for(const c of candidates){const trial={...c,slot,slot_label};p=buildOne(seed,trial,ctx,usedCompanions,new Set([...originalPrimaryIds,...usedPrimaryIds]),opts);if(p){chosenId=c.spot_id;break;}}}
      if(p){plans.push(p);usedPrimaryIds.add(chosenId);const primary=spotMap(seed).get(chosenId);if(primary)usedGroups.add(groupKey(primary));}
    }return plans;}
  return{buildPlans,areaKey,categoryKind,complementScore,durationLabel,requestedDurationLabel,minCoverageMinutes,shouldStaySingle,coverageMinutes,coverageOk};
});
