(function(root,factory){
  if(typeof module==='object'&&module.exports)module.exports=factory(require('./recommender.js'));
  else root.KibunPlans=factory(root.OdekakeRecommender);
})(typeof globalThis!=='undefined'?globalThis:this,function(Recommender){
  const {baseScores,hardFilterReason}=Recommender||{};
  const clamp=(x,lo=0,hi=100)=>Math.max(lo,Math.min(hi,x));
  function spotMap(seed){return new Map((seed.spots||[]).map(s=>[s.spot_id,s]));}
  function areaKey(s){const text=`${s.city||''} ${s.address||''}`;if(/横浜市/.test(text))return'横浜市';if(/川崎市/.test(text))return'川崎市';if(/箱根町/.test(text))return'箱根町';if(/鎌倉市/.test(text))return'鎌倉市';if(/藤沢市/.test(text))return'藤沢市';if(/逗子市/.test(text))return'逗子市';if(/三浦市/.test(text))return'三浦市';if(/横須賀市/.test(text))return'横須賀市';if(/鴨川市/.test(text))return'鴨川市';if(/木更津市/.test(text))return'木更津市';if(/浦安市/.test(text))return'浦安市';if(/伊東市/.test(text))return'伊東市';if(/東伊豆町/.test(text))return'東伊豆町';return s.routing?.municipality||s.city||s.prefecture||'';}
  function groupKey(s){return s.recommendation_group||s.spot_id;}
  function categoryKind(s){const p=String(s.category_primary||'').toLowerCase(),x=[s.category_primary,...(s.categories||[])].join('|').toLowerCase();if(s.overnight||/hotel|stay|ryokan|resort/.test(p))return'stay';if(/creative|workshop|experience|craft|pottery|glass|fragrance|washi|interactive|music/.test(p))return'experience';if(/food|cafe|restaurant|market|dining/.test(p))return'food';if(/relax|spa|onsen|bath/.test(p))return'relax';if(/culture|museum|gallery|library|temple|stage|theater|art|architecture/.test(p))return'culture';if(/theme|zoo|aquarium|pool|play|amusement/.test(p))return'activity';if(/park|nature|garden|waterside|beach/.test(p))return'nature';if(/shopping|mall/.test(p))return'shopping';if(/workshop|experience|craft|pottery|glass|fragrance|washi/.test(x))return'experience';if(/museum|gallery|library|temple|stage|theater|culture/.test(x))return'culture';if(/food|cafe|restaurant|market|dining/.test(x))return'food';if(/shopping|mall/.test(x))return'shopping';if(/park|nature|garden|waterside|beach/.test(x))return'nature';return'other';}
  function complementScore(a,b){const ka=categoryKind(a),kb=categoryKind(b);if(ka===kb)return 30;if((ka==='activity'||ka==='culture'||ka==='experience'||ka==='nature')&&kb==='food')return 100;if(ka==='food'&&['culture','experience','nature','shopping'].includes(kb))return 92;if(ka==='activity'&&kb==='relax')return 88;if(ka==='culture'&&['food','nature','shopping'].includes(kb))return 86;if(ka==='experience'&&['food','shopping','nature'].includes(kb))return 86;if(ka==='nature'&&['food','relax'].includes(kb))return 84;if(ka==='shopping'&&kb==='food')return 90;if(kb==='stay')return 94;return 65;}
  function durationLabel(minutes,type){if(type==='overnight')return'1泊プラン';if(minutes<=120)return'1〜2時間';if(minutes<=240)return'半日プラン';if(minutes<=390)return'たっぷり半日';return'1日プラン';}
  function shouldStaySingle(s,displayMinutes){const stay=Number(s.stay_minutes_seed||120);if(s.overnight)return false;if(displayMinutes<=120)return true;if(stay>=Math.max(105,displayMinutes*.62))return true;if(stay>=150&&displayMinutes<=240)return true;return false;}
  function eligible(s,ctx,allowOvernight){if(!s)return false;const c={...ctx,allowOvernight,includeBrowseOnly:false};return typeof hardFilterReason==='function'?!hardFilterReason(s,c):s.recommendation_mode!=='browse_only'&&(allowOvernight||!s.overnight);}
  function rankedCompanions(seed,primary,ctx,remaining,used,opts={}){if(remaining<45)return[];const primaryArea=areaKey(primary);return (seed.spots||[]).filter(s=>s.spot_id!==primary.spot_id&&!used.has(s.spot_id)&&groupKey(s)!==groupKey(primary)&&areaKey(s)===primaryArea&&eligible(s,ctx,!!opts.allowOvernight)&&Number(s.stay_minutes_seed||120)<=Math.max(60,remaining+25)&&Number(s.stay_minutes_seed||120)>=35).map(s=>{const sc=typeof baseScores==='function'?baseScores(s,{...ctx,allowOvernight:!!opts.allowOvernight,availableMinutes:remaining}):{overall:70};const comp=complementScore(primary,s);const shortPenalty=Math.max(0,Number(s.stay_minutes_seed||120)-remaining)*.3;return{s,score:.62*Number(sc.overall||70)+.38*comp-shortPenalty};}).sort((a,b)=>b.score-a.score);
  }
  function singleTitle(s){if(s.editorial?.title)return s.editorial.title;const k=categoryKind(s);if(k==='activity')return`${s.name}で、今日は遊びきる。`;if(k==='culture')return`${s.name}を、時間を気にせず歩く。`;if(k==='experience')return`${s.name}で、手を動かす時間をつくる。`;if(k==='nature')return`${s.name}で、外の時間を長くする。`;if(k==='relax')return`${s.name}で、今日は何もしすぎない。`;if(k==='stay')return`${s.name}で、一日の終わりまで楽しむ。`;return`${s.name}を主役に、今日はここで過ごす。`;}
  function singleLead(s,displayMinutes){if(s.editorial?.lead)return s.editorial.lead;const d=durationLabel(Math.min(displayMinutes,Number(s.stay_minutes_seed||120)),'single'),k=categoryKind(s);if(k==='activity')return`次の予定を詰め込まず、ここを目的地に。${d}くらい、遊ぶことだけに時間を使う。`;if(k==='culture')return`展示や建築を急いで回らず、気になったところで立ち止まる。${d}をひとつの場所に預ける過ごし方。`;if(k==='experience')return`見るだけではなく、自分の手を動かす。${d}くらい、つくることを今日の主役に。`;return`移動を重ねず、この場所を今日の主役に。${d}くらい、急がず楽しむ過ごし方です。`;}
  function comboTitle(a,b,type){if(type==='overnight')return`${a.name}を楽しんで、今日は帰らない。`;const kb=categoryKind(b);if(kb==='food')return`${a.name}のあと、もう少しおいしい寄り道。`;if(categoryKind(a)==='food')return`食べるだけで終わらない、${areaKey(a)}の半日。`;return`${a.name}から、${b.name}へ。`;}
  function comboLead(a,b,type){if(type==='overnight')return`${a.name}を楽しんだあとは、${b.name}で一日をゆっくり終える。移動を増やしすぎず、昼から夜までひと続きに。`;return`${a.name}を中心に、${b.name}まで。ひとつの場所だけでは少し余る日に、詰め込みすぎない2ストップです。`;}
  function buildOne(seed,r,ctx,used,allPrimaryIds,opts){const map=spotMap(seed),primary=map.get(r.spot_id);if(!primary)return null;const displayMinutes=Number(opts.displayMinutes||ctx.availableMinutes||180);const base={plan_id:`plan_${r.slot||primary.spot_id}`,slot:r.slot,slot_label:r.slot_label,score:Number(r.scores?.overall||70),travel_minutes:r.travel_minutes??null,why:r.why||[],primary_spot_id:primary.spot_id};
    if(primary.overnight){const dayCandidates=rankedCompanions(seed,primary,{...ctx,allowOvernight:false},300,new Set([...used,...allPrimaryIds]),{allowOvernight:false});const day=dayCandidates[0]?.s;if(day){used.add(day.spot_id);return{...base,type:'overnight',duration_label:'1泊プラン',title:comboTitle(day,primary,'overnight'),lead:comboLead(day,primary,'overnight'),spot_ids:[day.spot_id,primary.spot_id],steps:[{spot_id:day.spot_id,role:'DAY',label:'昼の主役'},{spot_id:primary.spot_id,role:'STAY',label:'泊まる'}]};}return{...base,type:'overnight',duration_label:'1泊プラン',title:singleTitle(primary),lead:singleLead(primary,displayMinutes),spot_ids:[primary.spot_id],steps:[{spot_id:primary.spot_id,role:'STAY',label:'泊まる'}]};}
    if(shouldStaySingle(primary,displayMinutes)){return{...base,type:'single',duration_label:durationLabel(Number(primary.stay_minutes_seed||displayMinutes),'single'),title:singleTitle(primary),lead:singleLead(primary,displayMinutes),spot_ids:[primary.spot_id],steps:[{spot_id:primary.spot_id,role:'MAIN',label:'今日の主役'}]};}
    const remain=Math.max(0,displayMinutes-Number(primary.stay_minutes_seed||120)-30);const blocked=new Set([...used,...allPrimaryIds]);const companions=rankedCompanions(seed,primary,{...ctx,allowOvernight:false},remain,blocked,{allowOvernight:false});let companion=companions[0]?.s||null;
    if(!companion&&ctx.allowOvernight){const hotels=rankedCompanions(seed,primary,{...ctx,allowOvernight:true},720,blocked,{allowOvernight:true}).filter(x=>x.s.overnight);companion=hotels[0]?.s||null;if(companion){used.add(companion.spot_id);return{...base,type:'overnight',duration_label:'1泊プラン',title:comboTitle(primary,companion,'overnight'),lead:comboLead(primary,companion,'overnight'),spot_ids:[primary.spot_id,companion.spot_id],steps:[{spot_id:primary.spot_id,role:'DAY',label:'昼の主役'},{spot_id:companion.spot_id,role:'STAY',label:'泊まる'}]};}}
    if(companion){used.add(companion.spot_id);const total=Number(primary.stay_minutes_seed||120)+Number(companion.stay_minutes_seed||90)+30;return{...base,type:'combo',duration_label:durationLabel(total,'combo'),title:comboTitle(primary,companion,'combo'),lead:comboLead(primary,companion,'combo'),spot_ids:[primary.spot_id,companion.spot_id],steps:[{spot_id:primary.spot_id,role:'MAIN',label:'まずここ'},{spot_id:companion.spot_id,role:'PLUS',label:'もうひとつ'}]};}
    return{...base,type:'single',duration_label:durationLabel(Number(primary.stay_minutes_seed||displayMinutes),'single'),title:singleTitle(primary),lead:singleLead(primary,displayMinutes),spot_ids:[primary.spot_id],steps:[{spot_id:primary.spot_id,role:'MAIN',label:'今日の主役'}]};
  }
  function buildPlans(seed,recommendationResult,ctx={},opts={}){const recs=recommendationResult?.recommendations||[],used=new Set(),allPrimaryIds=new Set(recs.map(r=>r.spot_id));const plans=[];for(const r of recs){const p=buildOne(seed,r,ctx,used,allPrimaryIds,opts);if(p)plans.push(p);}return plans;}
  return{buildPlans,areaKey,categoryKind,complementScore,durationLabel,shouldStaySingle};
});
