(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.OdekakeRecommender = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  const DEFAULT_VIBE_WEIGHTS=[1,.7,.7];
  const clamp=(x,lo=0,hi=100)=>Math.max(lo,Math.min(hi,x));
  function weightedMean(values,neutral=70){if(!values.length)return neutral;const den=values.reduce((a,[,w])=>a+w,0);return den?values.reduce((a,[v,w])=>a+v*w,0)/den:neutral;}
  function vibeMatchScore(spot,selected){if(!selected?.length)return 70;if(selected.length>3)throw new Error('気分は最大3つまでです');return weightedMean(selected.map((v,i)=>{if(!(v in (spot.vibes_seed||{})))throw new Error(`未知のvibe: ${v}`);return [Number(spot.vibes_seed[v]),DEFAULT_VIBE_WEIGHTS[i]];}));}
  function ageFitScore(spot,ageMonths){if(ageMonths===null||ageMonths===undefined||ageMonths==='')return 70;const e=spot.experience_seed||{},baby=Number(e.baby_fit??50),toddler=Number(e.toddler_fit??50),age=Number(ageMonths);if(age<18)return baby;if(age<48)return toddler;return .7*toddler+30;}
  function audienceFitScore(spot,audience){return Number((spot.audience_fit||{})[audience||'family']??70);}
  function weatherFitScore(spot,weather){const e=spot.experience_seed||{};if(!weather||weather==='any')return 70;if(weather==='rain')return Number(e.rain_resilience??50);if(weather==='hot')return Number(e.heat_resilience??50);if(weather==='clear')return clamp(65+.15*Math.max(Number(e.outdoor??50),Number(e.indoor??50)));if(weather==='cold')return clamp(55+.4*Number(e.indoor??50));return 70;}
  function timeFitScore(spot,m){if(!m)return 70;const stay=Number(spot.stay_minutes_seed||120);if(Number(m)>=stay){const margin=Math.min(Number(m)-stay,stay);return clamp(90+10*margin/Math.max(stay,1));}return clamp(90-85*(stay-Number(m))/Math.max(stay,1));}
  function travelFitScore(id,max,map){if(!max||!map||!(id in map))return 70;return clamp(100-48*Number(map[id])/Math.max(Number(max),1));}
  function jstDateKey(value){const d=value?new Date(value):new Date();if(Number.isNaN(d.getTime()))return null;const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const m=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${m.year}-${m.month}-${m.day}`;}
  function inDateRange(day,range){if(!day||!range)return false;const from=range.from||'0000-01-01',until=range.until||'9999-12-31';return day>=from&&day<=until;}
  function availabilityConstraintReason(avc,ctx){if(!avc||!Object.keys(avc).length)return null;const now=ctx.currentDate?new Date(ctx.currentDate):new Date();if(avc.unavailable_until){const resume=new Date(`${avc.unavailable_until}T00:00:00+09:00`);if(!Number.isNaN(resume.getTime())&&now<resume)return avc.note||'現在は利用できない';}const day=jstDateKey(now);if(!day)return null;const available=Array.isArray(avc.available_ranges)?avc.available_ranges:[];if(available.length&&!available.some(r=>inDateRange(day,r)))return avc.note||'営業期間外';const unavailable=Array.isArray(avc.unavailable_ranges)?avc.unavailable_ranges:[];const blocked=unavailable.find(r=>inDateRange(day,r));if(blocked)return blocked.note||avc.note||'休館・休業日';return null;}
  function shoppingIntentEligible(spot){const p=String(spot?.category_primary||'').toLowerCase(),v=Number(spot?.vibes_seed?.shopping||0);if(v<75)return false;if(/theme|amusement|aquarium|zoo|pool|water_resort|resort_pool|entertainment_park|character_theme/.test(p))return false;return /shopping|mall|outlet|market|mixed_use|urban_.*complex|culture_complex|lifestyle|district|street|t-site|wellbeing_complex/.test(p)||(/shopping/.test((spot?.categories||[]).join('|').toLowerCase())&&!/theme|amusement|aquarium|zoo|pool/.test(p));}
  function hardFilterReason(spot,ctx){const sid=spot.spot_id;if(spot.recommendation_mode==='browse_only'&&!ctx.includeBrowseOnly)return '日時指定型スポットはブラウズ向け';if(spot.overnight&&!ctx.allowOvernight)return '宿泊候補はオフ';if((ctx.selectedVibes||[]).includes('shopping')&&!shoppingIntentEligible(spot))return '買い物を主役にしやすい候補ではない';const age=(ctx.childAgeMonths===null||ctx.childAgeMonths===undefined||ctx.childAgeMonths==='')?null:Number(ctx.childAgeMonths);const ac=spot.age_constraints||{};if(age!==null&&!ac.soft){if(ac.min_months!==undefined&&age<Number(ac.min_months))return ac.note||'年齢条件に合わない';if(ac.max_months!==undefined&&age>Number(ac.max_months))return ac.note||'年齢条件に合わない';}const avc=spot.availability_constraints||{};const constraintReason=availabilityConstraintReason(avc,ctx);if(constraintReason)return constraintReason;const av=(ctx.availabilityBySpot||{})[sid]||{};for(const [key,label] of [['is_open','営業していない'],['reservation_available','予約枠がない'],['age_allowed','年齢条件に合わない']]){const val=av[key];if(val===false)return label;if(ctx.requireKnownAvailability&&(val===null||val===undefined))return `${key} が未確認`;}
    if(ctx.maxTravelMinutes){if(ctx.requireKnownTravel&&(!ctx.travelMinutesBySpot||!(sid in ctx.travelMinutesBySpot)))return '所要時間を取得できない';if(ctx.travelMinutesBySpot&&sid in ctx.travelMinutesBySpot&&Number(ctx.travelMinutesBySpot[sid])>Number(ctx.maxTravelMinutes))return '移動時間が上限を超える';}return null;}
  function baseScores(spot,ctx){const legacy=!ctx.audience;const audience=legacy?70:audienceFitScore(spot,ctx.audience);const hasChild=legacy?(ctx.childAgeMonths!==null&&ctx.childAgeMonths!==undefined&&ctx.childAgeMonths!==''):ctx.audience==='family'&&ctx.childAgeMonths!==null&&ctx.childAgeMonths!==undefined&&ctx.childAgeMonths!=='';const scores={vibe:vibeMatchScore(spot,ctx.selectedVibes||[]),audience,age:hasChild?ageFitScore(spot,ctx.childAgeMonths):70,weather:weatherFitScore(spot,ctx.weather),time:timeFitScore(spot,ctx.availableMinutes),travel:travelFitScore(spot.spot_id,ctx.maxTravelMinutes,ctx.travelMinutesBySpot)};
    const weights=legacy?{vibe:.55,audience:0,age:.15,weather:.10,time:.10,travel:.10}:hasChild?{vibe:.47,audience:.13,age:.12,weather:.09,time:.09,travel:.10}:{vibe:.50,audience:.20,age:0,weather:.10,time:.09,travel:.11};scores.overall=Object.entries(weights).reduce((sum,[k,w])=>sum+scores[k]*w,0);if(ctx.allowOvernight&&spot.overnight)scores.overall=clamp(scores.overall+8);return scores;}
  function easyScore(spot,overall,audience='family'){const e=spot.experience_seed||{},v=spot.vibes_seed||{},ease=100-Number(e.planning_friction??50),lowWalk=100-Number(e.walking_load??50),rest=Number(e.parent_rest??50),quiet=Number(e.quietness??50),adult=Number(spot.adult_enjoyment_seed??50);if(audience==='partner')return .48*overall+.16*ease+.12*quiet+.12*adult+.12*Number(v.relax??50);if(audience==='solo')return .46*overall+.18*ease+.17*quiet+.11*lowWalk+.08*adult;if(audience==='friends')return .52*overall+.16*ease+.12*Number(e.food_experience??50)+.10*lowWalk+.10*Number(e.hands_on??50);return .45*overall+.25*ease+.15*lowWalk+.15*rest;}
  function adventureScore(spot,overall,bestCat){const extra=Number((spot.vibes_seed||{}).extraordinary??50),active=Number((spot.experience_seed||{}).physical_activity??50);let score=.60*overall+.28*extra+.12*active;if(bestCat&&spot.category_primary===bestCat)score-=12;return score;}
  function reasonLines(spot,ctx,scores){const lines=[],v=spot.vibes_seed||{},e=spot.experience_seed||{},aud=ctx.audience||'family';for(const vibe of (ctx.selectedVibes||[]).slice(0,2)){const val=v[vibe];if(val!==undefined&&val>=75)lines.push(`${vibe} が強い（${Math.round(val)}）`);}if(aud==='family'){if(scores.audience>=86)lines.push('子どもと一緒に過ごしやすい');if(ctx.childAgeMonths!==null&&ctx.childAgeMonths!==undefined&&ctx.childAgeMonths!==''&&scores.age>=85)lines.push('子どもの年齢との相性が良い');}else if(aud==='partner'){if(scores.audience>=86)lines.push('ふたりで過ごす休日に向いている');if(Number(v.scenic??0)>=80)lines.push('景色も一緒に楽しみやすい');else if(Number(v.food??0)>=80)lines.push('食事やカフェを組み合わせやすい');else if(Number(v.relax??0)>=80)lines.push('急がずゆっくり過ごしやすい');}else if(aud==='solo'){if(scores.audience>=86)lines.push('ひとりで自分のペースを作りやすい');if(Number(e.quietness??0)>=75)lines.push('落ち着いて過ごしやすい');else if(Number(v.culture??0)>=80)lines.push('ひとりでじっくり見て回りやすい');}else if(aud==='friends'){if(scores.audience>=86)lines.push('友だちと一緒に楽しみやすい');if(Number(e.hands_on??0)>=75||Number(v.active??0)>=80)lines.push('一緒に体験して盛り上がりやすい');else if(Number(v.food??0)>=80||Number(v.shopping??0)>=80)lines.push('食べる・見るを一緒に楽しみやすい');}if(spot.overnight&&ctx.allowOvernight)lines.push('泊まりで日常を切り替えやすい');if(ctx.weather==='hot'&&scores.weather>=85)lines.push('暑い日でも過ごしやすい');if(ctx.weather==='rain'&&scores.weather>=85)lines.push('雨でも過ごしやすい');if(ctx.travelMinutesBySpot?.[spot.spot_id]!=null)lines.push(`${ctx.travelMinutesBySpot[spot.spot_id]}分くらいで行けそう`);if(!lines.length&&spot.public_copy)lines.push(spot.public_copy);return [...new Set(lines)].slice(0,3);}
  function slotLabels(audience){return audience==='partner'?{best_match:'いちばんハマる',adventure:'ちょっと特別',easy:'ゆっくり過ごす'}:audience==='solo'?{best_match:'いちばんハマる',adventure:'気分転換',easy:'自分のペース'}:audience==='friends'?{best_match:'いちばんハマる',adventure:'盛り上がる',easy:'ゆるく楽しむ'}:{best_match:'いちばんハマる',adventure:'ちょっと冒険',easy:'無理しない'};}
  function payload(spot,ctx,scores){return {spot_id:spot.spot_id,name:spot.name,slug:spot.slug,category_primary:spot.category_primary,public_copy:spot.public_copy,scores:Object.fromEntries(Object.entries(scores).map(([k,v])=>[k,Math.round(v*10)/10])),travel_minutes:ctx.travelMinutesBySpot?.[spot.spot_id]??null,why:reasonLines(spot,ctx,scores)};}
  function recommend(seed,ctx){const valid=new Set(Object.keys(seed.vibe_definitions||{})),selected=ctx.selectedVibes||[],unknown=selected.filter(v=>!valid.has(v));if(unknown.length)throw new Error(`未知のvibe: ${unknown.join(', ')}`);if(selected.length>3)throw new Error('気分は最大3つまでです');const candidates=[],excluded=[];for(const spot of seed.spots||[]){const reason=hardFilterReason(spot,ctx);if(reason)excluded.push({spot_id:spot.spot_id,name:spot.name,reason});else candidates.push([spot,baseScores(spot,ctx)]);}if(!candidates.length)return {recommendations:[],coverage_warning:'条件に合う候補がありません。',excluded};if(selected.length){const primary=selected[0],maxPrimary=Math.max(...candidates.map(([s])=>Number((s.vibes_seed||{})[primary]||0))),maxVibe=Math.max(...candidates.map(([,sc])=>sc.vibe));if(maxPrimary<35||maxVibe<35)return {input:ctx,recommendations:[],coverage_warning:'選んだ気分にぴったりと言えるスポットが、今のDBにはまだ少ないようです。',excluded};}
    candidates.sort((a,b)=>b[1].overall-a[1].overall);const groupKey=s=>s.recommendation_group||s.spot_id;const [bestSpot,bestScores]=candidates[0],used=new Set([bestSpot.spot_id]),usedGroups=new Set([groupKey(bestSpot)]),minVibe=selected.length?45:0;const rem1=candidates.filter(([s,sc])=>!used.has(s.spot_id)&&!usedGroups.has(groupKey(s))&&sc.vibe>=minVibe);let adventure=null;if(rem1.length){adventure=rem1.reduce((best,cur)=>{const score=adventureScore(cur[0],cur[1].overall,bestSpot.category_primary);return !best||score>best.score?{pair:cur,score}:best;},null);used.add(adventure.pair[0].spot_id);usedGroups.add(groupKey(adventure.pair[0]));}const rem2=candidates.filter(([s,sc])=>!used.has(s.spot_id)&&!usedGroups.has(groupKey(s))&&sc.vibe>=minVibe);let easy=null;if(rem2.length)easy=rem2.reduce((best,cur)=>{const score=easyScore(cur[0],cur[1].overall,ctx.audience||'family');return !best||score>best.score?{pair:cur,score}:best;},null);const labels=slotLabels(ctx.audience||'family'),recs=[];let p=payload(bestSpot,ctx,bestScores);p.slot='best_match';p.slot_label=labels.best_match;recs.push(p);if(adventure){p=payload(adventure.pair[0],ctx,adventure.pair[1]);p.slot='adventure';p.slot_label=labels.adventure;recs.push(p);}if(easy){p=payload(easy.pair[0],ctx,easy.pair[1]);p.slot='easy';p.slot_label=labels.easy;recs.push(p);}return {input:ctx,recommendations:recs,coverage_warning:null,excluded};}
  return {recommend,baseScores,hardFilterReason,shoppingIntentEligible,vibeMatchScore,ageFitScore,audienceFitScore,weatherFitScore,timeFitScore,easyScore,adventureScore,slotLabels};
});