const assert=require('assert');
const fs=require('fs');
const app=fs.readFileSync('app.js','utf8');
const html=fs.readFileSync('index.html','utf8');
assert.match(app,/browseRegion='all',browseCategory='all'/);
assert.match(app,/regionMatch\(s,browseRegion\)&&categoryMatch\(s,browseCategory\)/);
assert.ok(html.includes('browseRegionFilters'));
assert.ok(html.includes('browseCategoryFilters'));
assert.ok(!html.includes('data-browse-mode="region"'));
assert.ok(html.includes('地域とカテゴリは選ぶだけ。2つを掛け合わせて'));
console.log('V19.4.1 PASS: browse supports region x category AND filtering');
