const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const index=read('sns-audit/index.html');
const audit=read('sns-audit/audit.js');
const images=read('sns-audit/image-audit.js');
assert.ok(index.includes('image-audit.js?v=20117'),'image audit cache version missing');
assert.ok(index.includes('audit.js?v=20117'),'audit cache version missing');
assert.ok(images.includes("const VERSION='20.11.7'"),'image audit version missing');
assert.ok(images.includes('async function wikidataLeadImage'),'Wikidata resolver missing');
assert.ok(images.includes('async function commonsCategoryCandidates'),'Commons category resolver missing');
assert.ok(images.includes('async function autoFindSafe'),'auto open photo resolver missing');
assert.ok(images.includes("'チームラボボーダレス':['teamLab Borderless Azabudai Hills'"),'Tokyo query hint missing');
assert.ok(images.includes('autoFindSafe,render'),'autoFindSafe not exported');
assert.ok(audit.includes('async function resolveAutoSnsImages'),'capture auto photo injection missing');
assert.ok(audit.includes('data-auto-sns-spot'),'auto photo target marker missing');
assert.ok(audit.includes("if(imageMode==='safe')resolveAutoSnsImages(document)"),'safe capture does not trigger auto lookup');
assert.ok(audit.includes('Wikidata / Wikimedia Commons'),'capture explanation missing');
console.log('v20.11.7 auto open photos: PASS');
