const fs=require('fs'),assert=require('assert');
const seed=require('./seed.json');
const Plans=require('./plans.js');
const Rec=require('./recommender.js');
assert.ok(seed.spots.length>=306,'spot count');
const m=new Map(seed.spots.map(s=>[s.spot_id,s]));
for(const id of ['spot_301','spot_302','spot_303','spot_304','spot_305','spot_306'])assert.ok(m.has(id),id);
assert.strictEqual(m.get('spot_012').recommendation_mode,'browse_only');
assert.match(m.get('spot_039').dynamic_snapshot.temporary_note,/8月12日/);
assert.match(m.get('spot_102').dynamic_snapshot.temporary_note,/OTO-RACTION PARK/);
assert.strictEqual(m.get('spot_303').age_constraints.min_months,84);assert.match(m.get('spot_303').dynamic_snapshot.age_note,/110cm/);
assert.ok(Rec.hardFilterReason(m.get('spot_303'),{selectedVibes:[],audience:'family',childAgeMonths:18})?.includes('7歳未満'));
assert.ok(Plans.curatedPlanPreview(seed,'family_umi_no_koen_sea_cafe'));
const hp=Plans.curatedPlanPreview(seed,'family_hayama_art_garden_cafe');assert.ok(hp);assert.match(hp.availability_note,/9月11日/);
assert.ok(Plans.curatedPlanPreview(seed,'partner_yokohama_mars_walk_food'));
const browse=fs.readFileSync('app.js','utf8');assert.ok(browse.includes('let items=seed.spots.filter'),'browse must include browse_only spot');
const idx=fs.readFileSync('index.html','utf8');assert.ok(/\d+スポット/.test(idx));
const mag=fs.readFileSync('magazine/yokohama-family-cafe/index.html','utf8');assert.ok(mag.includes('横浜のカフェ7選'));assert.ok(mag.includes('spot_302'));
console.log('V20.1 PASS: 306 spots + vibe expansion + curated plans + unko browse-only');
