const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=__dirname;
function loadWindow(file,key){const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(`${root}/${file}`,'utf8'),ctx);return ctx.window[key];}
const seed=loadWindow('data.js','ODEKAKE_SEED');
const cfg=loadWindow('affiliate-config.js','KIBUN_AFFILIATE_CONFIG');
const audit=loadWindow('affiliate-audit-status.js','KIBUN_AFFILIATE_AUDIT_STATUS');
const config=loadWindow('config.js','KIBUN_CONFIG');
const worker=fs.readFileSync(`${root}/worker/worker.js`,'utf8');
const app=fs.readFileSync(`${root}/app.js`,'utf8');
const auditHtml=fs.readFileSync(`${root}/affiliate-audit/index.html`,'utf8');
const css=fs.readFileSync(`${root}/styles.css`,'utf8');
assert.equal(seed.spots.length,431);
assert.equal(Object.keys(cfg.sourceLinks).length,148);
assert.equal(Object.values(cfg.sourceLinks).flat().length,159);
assert.equal(Object.keys(audit.spots).length,431);
assert.equal(audit.distribution.configured,148);
assert.equal(audit.distribution.recheck_needed,127);
assert.equal(audit.distribution.not_target,140);
assert.equal(config.heroAuditCandidateCount,10);
assert.ok(worker.includes('Math.min(10'));
assert.ok(worker.includes("url.searchParams.get('limit')||10"));
assert.ok(worker.includes('photos.slice(0,10)'));
assert.ok(app.includes('最大10枚'));
assert.ok(app.includes('heroAuditCandidateCount||10'));
assert.ok(auditHtml.includes('affiliate-audit-status.js?v=2090'));
assert.ok(auditHtml.includes('id="auditOutcomeFilter"'));
assert.ok(auditHtml.includes('<option value="recheck_needed" selected>再調査</option>'));
assert.ok(css.includes('.image-shell{position:relative;display:block;width:100%;height:100%;overflow:hidden}'));
for(const sid of ['spot_040','spot_174','spot_246','spot_247','spot_255','spot_286','spot_321','spot_368','spot_386','spot_426']) assert.ok(cfg.sourceLinks[sid]?.length,`${sid} should be configured`);
console.log('v20.9.0 checks passed');
