const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const sns=read('sns-audit/index.html');
const js=read('sns-audit/audit.js');
const seed=read('sns-audit-data.js');
const aff=read('affiliate-audit/index.html');
const app=read('app.js');
assert.ok(index.includes('snsAudit')&&index.includes('sns-audit/'),'snsAudit redirect missing');
assert.ok(sns.includes('SNS AUDIT')&&sns.includes('使用Hero')&&sns.includes('Instagram導線')&&sns.includes('Affiliate準備状況')&&sns.includes('投稿実績'),'SNS audit fields missing');
assert.ok(js.includes('kibun-sns-audit-v2091')&&js.includes('localStorage')&&js.includes('downloadJson')&&js.includes('affiliateSummary'),'SNS audit persistence/export missing');
assert.ok(seed.includes('2026-09-30')&&seed.includes('9/30 投稿'),'9/30 seed missing');
assert.ok(aff.includes('../sns-audit/'),'Affiliate Audit -> SNS Audit nav missing');
assert.ok(app.includes('hero-audit-sns')&&app.includes('sns-audit/'),'Hero Audit -> SNS Audit nav missing');
console.log('v20.9.1 SNS audit integration: PASS');
