const fs=require('fs');const vm=require('vm');const assert=require('assert');const root=__dirname;const read=f=>fs.readFileSync(root+'/'+f,'utf8');
const ctx={window:{}};vm.createContext(ctx);vm.runInContext(read('data.js'),ctx);vm.runInContext(read('affiliate-config.js'),ctx);const seed=ctx.window.ODEKAKE_SEED,cfg=ctx.window.KIBUN_AFFILIATE_CONFIG;
assert.ok(seed.spots.length>=317,'spot count');assert.ok(/^0\.20\.\d+(?:\.\d+)?(?:\.\d+)?$/.test(seed.metadata.version));
assert.equal(seed.spots.find(s=>s.spot_id==='spot_301').media_strategy.google_places.photo_index_override,0);
assert.equal(seed.spots.find(s=>s.spot_id==='spot_213').media_strategy.google_places.place_id,'ChIJz7WQw9meGWAR8_Ijv9AMs4Q');
assert.equal(cfg.linkSwitch.enabled,true);assert.equal(cfg.linkSwitch.tagInstalled,true);assert.ok(cfg.linkSwitch.providers.includes('ozmall'));assert.ok(cfg.sourceLinks.spot_307[0].url.includes('ozmall.co.jp/restaurant/8313'));
['affiliate-audit/index.html','affiliate-audit/audit.css','affiliate-audit/audit.js'].forEach(f=>assert.ok(fs.existsSync(root+'/'+f),f));
const audit=read('affiliate-audit/index.html'),js=read('affiliate-audit/audit.js'),idx=read('index.html');
assert.ok(/noindex,nofollow/.test(audit));assert.ok(/linkSwitchProbe/.test(audit));assert.ok(/dalr\\\.valuecommerce\\\.com|dalr\\.valuecommerce\\.com/.test(js));assert.ok(/source_link_overrides/.test(js));assert.ok(/manual_link_overrides/.test(js));assert.ok(/affiliateAudit/.test(idx));assert.ok(/892690966/.test(idx));assert.ok(/aml\.valuecommerce\.com\/vcdal\.js/.test(idx));
const aCtx={window:{KIBUN_AFFILIATE_CONFIG:cfg}};vm.createContext(aCtx);vm.runInContext(read('affiliate.js'),aCtx);const spot=seed.spots.find(s=>s.spot_id==='spot_307');assert.ok(aCtx.window.KibunAffiliate.sourceLinksFor(spot).length>=1);
console.log('v20.5 affiliate live tests passed');
