const assert=require('assert');const fs=require('fs');const vm=require('vm');
const ctx={window:{}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/data.js','utf8'),ctx);const seed=ctx.window.ODEKAKE_SEED;
assert.ok(/^0\.20\.(?:7\.0|8\.0|8\.1|8\.2|10\.0|10\.1)$/.test(seed.metadata.version));assert.ok(seed.spots.length>=387);
const ids=seed.spots.map(s=>s.spot_id),slugs=seed.spots.map(s=>s.slug),names=new Set(seed.spots.map(s=>s.name));
assert.strictEqual(new Set(ids).size,ids.length);assert.strictEqual(new Set(slugs).size,slugs.length);
const expected=["清里テラス", "城ヶ島", "長瀞岩畳", "大山寺", "アサヒスカイルーム", "表参道バンブー", "Cafe Bell", "オリエント・カフェ", "BUNDAN COFFEE & BEER", "CANADE LOUNGE", "迎賓館赤坂離宮", "café TEIEN", "Café 1894", "dotcom coffee Asakusabashi", "ARC", "UNISON TAILOR", "CONTAINER", "Rain On The Roof", "Common cafe&music bar lounge", "uRn.chAi&TeA ルミネ新宿店", "OMOカフェ＆バル（OMO5東京五反田）", "EAT GOOD PLACE", "OGAWA COFFEE LABORATORY 高輪", "LOOPS", "サロン・ド・テ ロンド", "goodcoffee 新橋", "Sfumato", "田園調布せせらぎ館", "VAT BAKERY", "PARC CAFE at TOE LIBRARY", "BREWS", "felice domani nakameguro", "Factory & Labo 神乃珈琲", "橙子猫 Orange Cat", "SHARE LOUNGE MARUNOUCHI", "ampere 本の森ちゅうおう", "WeLoveDonut 神楽坂店", "SISIRI 恵比寿店", "Monkey Cafe", "GLITCH COFFEE TOKYO 日本橋本町", "yoka／余暇", "EN", "Bacha Coffee 新丸ビル", "ちいさな硝子の本の博物館", "みそめぼれ", "AIGIS 東京・表参道店", "喫茶ゆうびん屋", "HININE NOTE 代々木公園店", "VANILLABEANS THE ROASTERY HAMMERHEAD", "もみの気ハウス 渋谷道玄坂店", "梅体験専門店「蝶矢」鎌倉店", "AP LAB Tokyo", "Re:MAKE OUTLET レイクタウンアウトレット", "クレヨンしんちゃん オカシナもぐもぐワールド", "丸亀製麺 手づくり体験教室 東京立川", "シルバニアファミリー 森の大きなお家 東京ソラマチ店", "大慶園", "nanetokyo", "Pippi", "まもなく済州ビーチ", "Animal Cafe 爬にまるカフェ", "my clay story", "＋add"];for(const n of expected)assert.ok(names.has(n),'missing catch-up spot: '+n);
for(const n of ['べるべるパーク新宿本店','べるべるパーク渋谷店','coしぶや（渋谷区子育てネウボラ）','うんこミュージアム YOKOHAMA BAY','神奈川県立近代美術館 葉山','大雄山最乗寺'])assert.ok(names.has(n),'legacy requested spot missing: '+n);
const app=fs.readFileSync(__dirname+'/app.js','utf8'),idx=fs.readFileSync(__dirname+'/index.html','utf8');assert.ok(app.includes('Instagramでこのスポットを検索')||app.includes('Instagramで投稿を見る'));assert.ok(app.includes('公式Instagramを見る'));assert.ok(/(?:387|431|446)スポット/.test(idx));
for(const s of seed.spots){assert.ok(s.name&&s.address&&s.official_url,s.spot_id);assert.strictEqual(Object.keys(s.vibes_seed||{}).length,13,s.name);assert.strictEqual(Object.keys(s.experience_seed||{}).length,18,s.name);}
console.log('v20.7.0 catch-up regression passed: 63 catch-up spots preserved');
