const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={window:{},document:{getElementById:()=>null,createElement:()=>({setAttribute(){},appendChild(){}}),body:{appendChild(){}}}};vm.createContext(ctx);
vm.runInContext(fs.readFileSync('affiliate-config.js','utf8'),ctx);
const cfg=ctx.window.KIBUN_AFFILIATE_CONFIG;
assert(cfg.linkSwitch.providers.includes('asoview'));
assert(cfg.linkSwitch.providers.includes('jalan_activity'));
assert(cfg.linkSwitch.providers.includes('klook'));
assert(!cfg.linkSwitch.providers.includes('activity_japan'));
assert.deepStrictEqual(Array.from(cfg.providerPriorityOverseas.experience),['klook']);
for(const p of ['asoview','jalan_activity','activity_japan','klook']) assert(cfg.providerLabels[p]);
const audit=fs.readFileSync('affiliate-audit/audit.js','utf8');
for(const p of ['jalan_activity','activity_japan','klook']) assert(audit.includes(p));
assert(audit.includes("[/訪日OTA/i,'klook']"));
assert(audit.includes('activityJapanEligible'));
const app=fs.readFileSync('app.js','utf8');
assert(app.includes("['overseas','海外']"));
assert(app.includes('function countryCode'));
assert(app.includes('function areaLabel'));
console.log('v20.6 activity/overseas tests passed');
