const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const path=require('path');
const P=require('./plans.js');
const seed=JSON.parse(fs.readFileSync(path.join(__dirname,'seed.json'),'utf8'));
assert.equal(seed.spots.length,286,'v19.8.3 should contain 286 spots');
assert.equal(seed.metadata.version,'0.19.8.3');
for(let i=257;i<=286;i++)assert.ok(seed.spots.some(s=>s.spot_id===`spot_${String(i).padStart(3,'0')}`),`missing spot_${i}`);
const foodNew=seed.spots.filter(s=>Number(s.spot_id.slice(5))>=257&&Number(s.spot_id.slice(5))<=284);
assert.equal(foodNew.length,28,'28 food/cafe additions');
assert.ok(foodNew.every(s=>P.isMealSpot(s)),'all 28 food/cafe additions should be meal spots');
assert.ok(foodNew.every(s=>s.plan_profile?.zone&&s.plan_profile?.role==='companion'),'food spots need plan zones and companion role');

const odaiba=seed.spots.find(s=>s.spot_id==='spot_149');
const midtown=seed.spots.find(s=>s.name==='東京ミッドタウン');
const miraikan=seed.spots.find(s=>s.name==='日本科学未来館');
const eggs=seed.spots.find(s=>s.name==='Eggs ’n Things お台場店');
assert.equal(P.planZone(odaiba),'odaiba');
assert.equal(P.planZone(midtown),'roppongi');
assert.equal(P.samePlanArea(odaiba,midtown),false,'Odaiba and Midtown must not be a local plan cluster');
assert.equal(P.samePlanArea(odaiba,miraikan),true);
assert.equal(P.samePlanArea(odaiba,eggs),true);
const ctx={selectedVibes:['nature','food'],audience:'family',childAgeMonths:18,weather:'any',availableMinutes:480,allowOvernight:false};
const plan=P.buildPlans(seed,{recommendations:[{spot_id:'spot_149',slot:'best_match',slot_label:'いちばんハマる',scores:{overall:95},why:[]}]},ctx,{displayMinutes:480})[0];
assert.ok(plan,'Odaiba family plan should build');
assert.ok(!plan.spot_ids.includes(midtown.spot_id),'must not hop Odaiba -> Midtown');
assert.ok(plan.steps.some(x=>x.label==='子どもの時間'),'long family plan should include a child role');
assert.ok(plan.steps.some(x=>x.label==='ひと休み・ごはん'),'long family plan should include a meal/rest role');
assert.ok(plan.spot_ids.some(id=>P.isMealSpot(seed.spots.find(s=>s.spot_id===id))));

const sandbox={window:{}};vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(__dirname,'affiliate-config.js'),'utf8'),sandbox);
vm.runInContext(fs.readFileSync(path.join(__dirname,'affiliate.js'),'utf8'),sandbox);
const fujiyahotel=seed.spots.find(s=>s.spot_id==='spot_214');
const links=sandbox.window.KibunAffiliate.linksFor(fujiyahotel);
assert.equal(links.length,1,'curated booking shows one provider');
assert.equal(links[0].provider,'ozmall','OZmall should win for Fujiya Hotel');
assert.equal(links[0].scope,'spot','individual hotel link should beat area fallback');
assert.ok(links[0].rawHtml.includes('www.ozmall.co.jp%2Ftravel%2Fstay%2F1186%2F'));
assert.ok(sandbox.window.KibunAffiliate.allLinksFor(fujiyahotel).some(x=>x.provider==='jalan'),'Jalan remains as fallback');
console.log('V19.8.3 FOOD/AFFILIATE PASS: 286 spots + 28 food companions + micro zones + family roles + OZmall curated priority');
