const assert=require('assert');
const fs=require('fs');
const seed=JSON.parse(fs.readFileSync('seed.json','utf8'));
const index=fs.readFileSync('index.html','utf8');
const privacy=fs.readFileSync('privacy.html','utf8');
const workerToml=fs.readFileSync('worker/wrangler.toml','utf8');
assert.equal(seed.spots.length,286);
assert.ok(/^0\.19\.(?:5(?:\.\d+)?|6(?:\.\d+)?|7(?:\.\d+)?|8(?:\.\d+)?)$/.test(seed.metadata.version));
assert.equal(fs.readFileSync('CNAME','utf8').trim(),'kibuntrip.com');
assert.ok(index.includes('<link rel="canonical" href="https://kibuntrip.com/"'));
assert.ok(index.includes('property="og:image" content="https://kibuntrip.com/assets/og-kibuntrip.png"'));
assert.ok(index.includes('application/ld+json'));
assert.ok(fs.existsSync('assets/og-kibuntrip.png'));
assert.ok(fs.existsSync('favicon.svg'));
assert.ok(fs.existsSync('robots.txt'));
assert.ok(fs.readFileSync('robots.txt','utf8').includes('https://kibuntrip.com/sitemap.xml'));
assert.ok(fs.readFileSync('sitemap.xml','utf8').includes('https://kibuntrip.com/'));
assert.ok(privacy.includes('出発地の場所検索'));
assert.ok(workerToml.includes('https://kibuntrip.com'));
assert.ok(workerToml.includes('https://nnmsw07.github.io'));
console.log('V19.5 PASS: custom domain + SEO/OGP + legal disclosure + Worker CORS release prep');
