(function(){
  const KEY='kibun-sns-audit-v2091';
  const seed=window.KIBUN_SNS_AUDIT_SEED||{posts:[]};
  const spots=window.ODEKAKE_SEED?.spots||[];
  const aff=window.KIBUN_AFFILIATE_CONFIG||{};
  const affAudit=window.KIBUN_AFFILIATE_AUDIT_STATUS?.spots||{};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=x=>JSON.parse(JSON.stringify(x));
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x?.posts)return x}catch(_e){}return {posts:clone(seed.posts||[])};}
  let state=load();
  function persist(){localStorage.setItem(KEY,JSON.stringify(state));}
  function spotById(id){return spots.find(s=>s.spot_id===id)||null;}
  function affiliateSummary(spot){if(!spot)return 'スポット未指定';const links=[...(aff.links?.[spot.spot_id]||[]),...(aff.sourceLinks?.[spot.spot_id]||[])];if(links.length)return `リンク設定あり · ${links.length}件`;const a=affAudit[spot.spot_id];if(a?.status==='recheck_needed')return '再調査';if(a?.status==='researched_no_partner')return 'ASP商品なし確認';if(a?.status==='direct_only')return '公式導線のみ';if(a?.status==='not_target')return '対象外';return a?.status||'未確認';}
  function instagramSuggestion(spot){if(!spot)return'';const s=spot.social||spot.social_media||{};return s.instagram_url||s.instagram||s.reel_url||'';}
  function heroSuggestion(spot){return spot?.hero_image?.url||'';}
  function destinationSuggestion(post,spot){if(post.destination_type==='spot'&&spot)return `../?spot=${encodeURIComponent(spot.spot_id)}`;return'';}
  function newPost(){const id='post_'+Date.now();return{id,date:'',channel:'Instagram',title:'新しい投稿',status:'planned',destination_type:'',destination_url:'',spot_id:'',hero_ref:'',instagram_route:'',instagram_url:'',affiliate_status:'',result:{impressions:'',reach:'',saves:'',clicks:'',profile_visits:'',notes:''}};}
  function update(id,path,value){const p=state.posts.find(x=>x.id===id);if(!p)return;const parts=path.split('.');let o=p;while(parts.length>1){const k=parts.shift();o[k]??={};o=o[k];}o[parts[0]]=value;persist();renderSummary();}
  function statusLabel(x){return {planned:'予定',draft:'下書き',scheduled:'予約済み',published:'投稿済み'}[x]||x||'未設定';}
  function card(post){const spot=spotById(post.spot_id),affStatus=post.affiliate_status||affiliateSummary(spot),suggestHero=heroSuggestion(spot),suggestIg=instagramSuggestion(spot),suggestDest=destinationSuggestion(post,spot);return `<article class="post-card" data-id="${esc(post.id)}"><div class="post-head"><div><span class="post-id">${esc(post.id)}</span><h2>${esc(post.title||'投稿')}</h2><span class="status-chip">${esc(statusLabel(post.status))}</span></div><button class="remove-post" type="button" data-remove>削除</button></div><div class="grid">
  <label class="field"><span>投稿日</span><input data-field="date" type="date" value="${esc(post.date)}"></label>
  <label class="field"><span>Channel</span><select data-field="channel"><option${post.channel==='Instagram'?' selected':''}>Instagram</option><option${post.channel==='X'?' selected':''}>X</option><option${post.channel==='Note'?' selected':''}>Note</option><option${post.channel==='Other'?' selected':''}>Other</option></select></label>
  <label class="field full"><span>投稿名 / テーマ</span><input data-field="title" value="${esc(post.title)}"></label>
  <label class="field"><span>状態</span><select data-field="status"><option value="planned"${post.status==='planned'?' selected':''}>予定</option><option value="draft"${post.status==='draft'?' selected':''}>下書き</option><option value="scheduled"${post.status==='scheduled'?' selected':''}>予約済み</option><option value="published"${post.status==='published'?' selected':''}>投稿済み</option></select></label>
  <label class="field"><span>遷移先</span><select data-field="destination_type"><option value=""${!post.destination_type?' selected':''}>未設定</option><option value="article"${post.destination_type==='article'?' selected':''}>記事</option><option value="plan"${post.destination_type==='plan'?' selected':''}>プラン</option><option value="spot"${post.destination_type==='spot'?' selected':''}>スポット</option></select></label>
  <label class="field"><span>spot ID</span><input data-field="spot_id" value="${esc(post.spot_id)}" placeholder="spot_001"><small>${spot?esc(spot.name):'スポット投稿なら入力'}</small></label>
  <label class="field"><span>遷移URL</span><input data-field="destination_url" value="${esc(post.destination_url)}" placeholder="https://kibuntrip.com/..."><div class="mini-actions">${suggestDest?`<button type="button" data-fill="destination_url" data-value="${esc(suggestDest)}">スポットURLを補完</button>`:''}</div></label>
  <label class="field full"><span>使用Hero</span><input data-field="hero_ref" value="${esc(post.hero_ref)}" placeholder="assets/... または Google Places 選択Hero"><div class="mini-actions">${suggestHero?`<button type="button" data-fill="hero_ref" data-value="${esc(suggestHero)}">現在のHeroを補完</button>`:''}</div></label>
  <label class="field"><span>Instagram導線</span><select data-field="instagram_route"><option value=""${!post.instagram_route?' selected':''}>未設定</option><option value="official"${post.instagram_route==='official'?' selected':''}>公式Instagram</option><option value="reel"${post.instagram_route==='reel'?' selected':''}>公式Reel</option><option value="search"${post.instagram_route==='search'?' selected':''}>投稿検索</option><option value="none"${post.instagram_route==='none'?' selected':''}>なし</option></select></label>
  <label class="field"><span>Instagram URL</span><input data-field="instagram_url" value="${esc(post.instagram_url)}" placeholder="https://www.instagram.com/..."><div class="mini-actions">${suggestIg?`<button type="button" data-fill="instagram_url" data-value="${esc(suggestIg)}">登録済み導線を補完</button>`:''}</div></label>
  <label class="field full"><span>Affiliate準備状況</span><input data-field="affiliate_status" value="${esc(post.affiliate_status)}" placeholder="自動判定を使うなら空欄"><div class="readiness">自動判定: <strong>${esc(affiliateSummary(spot))}</strong></div></label>
</div><section class="result-box"><h3>投稿実績</h3><div class="result-grid">
  <label>Impressions<input data-field="result.impressions" inputmode="numeric" value="${esc(post.result?.impressions)}"></label><label>Reach<input data-field="result.reach" inputmode="numeric" value="${esc(post.result?.reach)}"></label><label>Saves<input data-field="result.saves" inputmode="numeric" value="${esc(post.result?.saves)}"></label><label>Clicks<input data-field="result.clicks" inputmode="numeric" value="${esc(post.result?.clicks)}"></label><label>Profile visits<input data-field="result.profile_visits" inputmode="numeric" value="${esc(post.result?.profile_visits)}"></label>
</div><label class="field result-notes"><span>メモ</span><textarea data-field="result.notes" rows="3">${esc(post.result?.notes)}</textarea></label></section></article>`;}
  function visible(){const q=$('textFilter').value.trim().toLowerCase(),st=$('statusFilter').value;return state.posts.filter(p=>(st==='all'||p.status===st)&&(!q||`${p.title} ${p.spot_id} ${p.destination_url}`.toLowerCase().includes(q)));}
  function renderSummary(){const all=state.posts,pub=all.filter(x=>x.status==='published').length,missingDest=all.filter(x=>!x.destination_url).length,missingHero=all.filter(x=>!x.hero_ref).length,missingIg=all.filter(x=>x.channel==='Instagram'&&!x.instagram_route).length;$('summary').innerHTML=`<span class="metric"><strong>${all.length}</strong> 投稿</span><span class="metric"><strong>${pub}</strong> 投稿済み</span><span class="metric"><strong>${missingDest}</strong> 遷移先未設定</span><span class="metric"><strong>${missingHero}</strong> Hero未設定</span><span class="metric"><strong>${missingIg}</strong> Instagram導線未設定</span>`;}
  function bind(){document.querySelectorAll('.post-card').forEach(card=>{const id=card.dataset.id;card.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change',()=>{update(id,el.dataset.field,el.value);render();}));card.querySelectorAll('[data-fill]').forEach(btn=>btn.addEventListener('click',()=>{update(id,btn.dataset.fill,btn.dataset.value);render();flash('補完しました')}));card.querySelector('[data-remove]')?.addEventListener('click',()=>{if(!confirm('この投稿を削除しますか？'))return;state.posts=state.posts.filter(x=>x.id!==id);persist();render();});});}
  function render(){renderSummary();const rows=visible();$('auditList').innerHTML=rows.length?rows.map(card).join(''):'<article class="post-card"><h2>該当する投稿はありません。</h2></article>';bind();}
  function exportData(){return {version:'20.9.1',exported_at:new Date().toISOString(),posts:state.posts};}
  async function copyText(text,msg){try{await navigator.clipboard.writeText(text)}catch(_e){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}flash(msg);}
  function flash(msg){$('flash').textContent=msg;clearTimeout(flash.t);flash.t=setTimeout(()=>$('flash').textContent='',2400);}
  $('addPost').addEventListener('click',()=>{state.posts.unshift(newPost());persist();$('statusFilter').value='all';render();flash('投稿を追加しました')});
  $('copyJson').addEventListener('click',()=>copyText(JSON.stringify(exportData(),null,2),'設定JSONをコピーしました'));
  $('downloadJson').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'}));a.download='kibun-sns-audit.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);flash('JSONを保存しました')});
  $('importJson').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!Array.isArray(obj.posts))throw new Error();state={posts:obj.posts};persist();render();flash('JSONを読み込みました')}catch(_e){flash('JSONを読み込めませんでした')}e.target.value='';});
  $('resetLocal').addEventListener('click',()=>{if(!confirm('SNS Auditの端末保存を初期化しますか？'))return;localStorage.removeItem(KEY);state={posts:clone(seed.posts||[])};render();flash('初期状態に戻しました')});
  $('textFilter').addEventListener('input',render);$('statusFilter').addEventListener('change',render);render();
})();
