(function(){
  const KEY='kibun-sns-audit-v2092',OLD_KEY='kibun-sns-audit-v2091';
  const seed=window.KIBUN_SNS_AUDIT_SEED||{posts:[]};
  const spots=window.ODEKAKE_SEED?.spots||[];
  const aff=window.KIBUN_AFFILIATE_CONFIG||{};
  const affAudit=window.KIBUN_AFFILIATE_AUDIT_STATUS?.spots||{};
  const copyTabs={};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=x=>JSON.parse(JSON.stringify(x));
  function deepMerge(a,b){if(Array.isArray(a))return b===undefined?clone(a):clone(b);if(a&&typeof a==='object'){const out=clone(a);Object.entries(b||{}).forEach(([k,v])=>out[k]=(k in out)?deepMerge(out[k],v):clone(v));return out}return b===undefined?a:b;}
  function isBlankLegacy(p){return p?.title==='9/30 投稿'&&!p?.destination_url&&!p?.spot_id&&!p?.hero_ref&&!p?.result?.impressions;}
  function mergeSeed(existing){const byId=new Map((existing||[]).filter(p=>!isBlankLegacy(p)).map(p=>[p.id,p]));const merged=(seed.posts||[]).map(s=>deepMerge(s,byId.get(s.id)||{}));for(const p of (existing||[])){if(!isBlankLegacy(p)&&!byId.has('__x')&&!seed.posts.some(s=>s.id===p.id))merged.unshift(normalize(p));}return {posts:merged};}
  function normalize(p){return deepMerge({id:'post_'+Date.now(),date:'',channel:'Instagram',title:'新しい投稿',pillar:'',goal:'',status:'planned',destination_type:'',destination_url:'',destination_title:'',destination_image:'',spot_id:'',hero_ref:'',instagram_route:'',instagram_url:'',affiliate_status:'',post_note:'',copy:{instagram:'',threads:''},hashtags:{instagram:'#今日のKibun #KibunTrip',threads:'#今日のKibun'},cta:{instagram:'',threads:''},creative:{instagram:'',threads:''},result:{impressions:'',reach:'',saves:'',shares:'',replies:'',site_clicks:'',outbound_clicks:'',profile_visits:'',notes:''}},p||{});}
  function load(){for(const key of [KEY,OLD_KEY]){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x?.posts)return mergeSeed(x.posts)}catch(_e){}}return {posts:clone(seed.posts||[])};}
  let state=load();
  function persist(){localStorage.setItem(KEY,JSON.stringify(state));}
  function spotById(id){return spots.find(s=>s.spot_id===id)||null;}
  function affiliateSummary(spot){if(!spot)return '記事/プラン内の導線を確認';const links=[...(aff.links?.[spot.spot_id]||[]),...(aff.sourceLinks?.[spot.spot_id]||[])];if(links.length)return `リンク設定あり · ${links.length}件`;const a=affAudit[spot.spot_id];if(a?.status==='recheck_needed')return '再調査';if(a?.status==='researched_no_partner')return 'ASP商品なし確認';if(a?.status==='direct_only')return '公式導線のみ';if(a?.status==='not_target')return '対象外';return a?.status||'未確認';}
  function instagramSuggestion(spot){if(!spot)return'';const s=spot.social||spot.social_media||{};return s.instagram_url||s.instagram||s.reel_url||'';}
  function heroSuggestion(spot){return spot?.hero_image?.url||'';}
  function destinationSuggestion(post,spot){if(post.destination_type==='spot'&&spot)return `../?spot=${encodeURIComponent(spot.spot_id)}&source=sns_audit`;return'';}
  function newPost(){return normalize({id:'post_'+Date.now(),date:'',channel:'Instagram',title:'新しい投稿'});}
  function getPath(o,path){return path.split('.').reduce((x,k)=>x?.[k],o);}
  function update(id,path,value){const p=state.posts.find(x=>x.id===id);if(!p)return;const parts=path.split('.');let o=p;while(parts.length>1){const k=parts.shift();o[k]??={};o=o[k];}o[parts[0]]=value;persist();renderSummary();}
  function statusLabel(x){return {planned:'予定',draft:'下書き',scheduled:'予約済み',published:'投稿済み'}[x]||x||'未設定';}
  function tabFor(post){return copyTabs[post.id]||(post.channel==='Threads'?'threads':'instagram');}
  function preview(post){if(!post.destination_url)return '<div class="destination-empty">遷移先を設定すると、ここから実ページを開けます。</div>';const image=post.hero_ref||post.destination_image;return `<div class="destination-card">${image?`<img src="${esc(image)}" alt="" onerror="this.style.display='none'">`:''}<div><strong>${esc(post.destination_title||post.title)}</strong><small>${esc(post.destination_url)}</small></div><a href="${esc(post.destination_url)}" target="_blank" rel="noopener">開く ↗</a></div>`;}
  function copyPanel(post,platform){const label=platform==='instagram'?'Instagram':'Threads';const chars=String(post.copy?.[platform]||'').length;return `<div class="copy-panel"><div class="copy-panel-head"><strong>${label} 完成原稿</strong><span>${chars}文字</span></div><textarea data-field="copy.${platform}" rows="11" placeholder="投稿原稿">${esc(post.copy?.[platform])}</textarea><div class="copy-buttons"><button type="button" data-copy="body" data-platform="${platform}">原稿をコピー</button><button type="button" data-copy="all" data-platform="${platform}" class="primary-mini">原稿＋ハッシュタグ</button></div><label class="field"><span>ハッシュタグ</span><textarea data-field="hashtags.${platform}" rows="2">${esc(post.hashtags?.[platform])}</textarea></label><label class="field"><span>CTA</span><input data-field="cta.${platform}" value="${esc(post.cta?.[platform])}"></label><label class="field"><span>画像 / カルーセル構成</span><textarea data-field="creative.${platform}" rows="4">${esc(post.creative?.[platform])}</textarea></label></div>`;}
  function card(post){const spot=spotById(post.spot_id),suggestHero=heroSuggestion(spot),suggestIg=instagramSuggestion(spot),suggestDest=destinationSuggestion(post,spot),active=tabFor(post),affStatus=post.affiliate_status||affiliateSummary(spot);return `<article class="post-card" data-id="${esc(post.id)}"><div class="post-head"><div><span class="post-id">${esc(post.date)} · ${esc(post.id)}</span><h2>${esc(post.title||'投稿')}</h2><div class="head-chips"><span class="status-chip">${esc(statusLabel(post.status))}</span>${post.pillar?`<span class="pillar-chip">${esc(post.pillar)}</span>`:''}</div></div><button class="remove-post" type="button" data-remove>削除</button></div>
  <label class="field status-wide"><span>状態</span><select data-field="status"><option value="planned"${post.status==='planned'?' selected':''}>予定</option><option value="draft"${post.status==='draft'?' selected':''}>下書き</option><option value="scheduled"${post.status==='scheduled'?' selected':''}>予約済み</option><option value="published"${post.status==='published'?' selected':''}>投稿済み</option></select></label>
  <section class="section-box copy-section"><div class="section-title"><span>PUBLISH COPY</span><strong>投稿原稿</strong><small>毎回考えなくてOK。必要ならここで直接直せます。</small></div><div class="copy-tabs" role="tablist"><button type="button" class="${active==='instagram'?'active':''}" data-copy-tab="instagram">Instagram</button><button type="button" class="${active==='threads'?'active':''}" data-copy-tab="threads">Threads</button></div>${copyPanel(post,active)}</section>
  <section class="section-box"><div class="section-title"><span>DESTINATION / CREATIVE</span><strong>どこへ届けるか</strong></div>${preview(post)}<div class="grid">
  <label class="field"><span>投稿日</span><input data-field="date" type="date" value="${esc(post.date)}"></label>
  <label class="field"><span>主媒体</span><select data-field="channel"><option${post.channel==='Instagram'?' selected':''}>Instagram</option><option${post.channel==='Threads'?' selected':''}>Threads</option><option${post.channel==='X'?' selected':''}>X</option><option${post.channel==='Note'?' selected':''}>Note</option><option${post.channel==='Other'?' selected':''}>Other</option></select></label>
  <label class="field full"><span>投稿名 / テーマ</span><input data-field="title" value="${esc(post.title)}"></label>
  <label class="field"><span>遷移先</span><select data-field="destination_type"><option value=""${!post.destination_type?' selected':''}>未設定</option><option value="article"${post.destination_type==='article'?' selected':''}>記事</option><option value="plan"${post.destination_type==='plan'?' selected':''}>プラン</option><option value="spot"${post.destination_type==='spot'?' selected':''}>スポット</option><option value="top"${post.destination_type==='top'?' selected':''}>トップ / 気分</option></select></label>
  <label class="field"><span>spot ID</span><input data-field="spot_id" value="${esc(post.spot_id)}" placeholder="spot_001"><small>${spot?esc(spot.name):'スポット投稿のみ入力'}</small></label>
  <label class="field full"><span>遷移URL</span><input data-field="destination_url" value="${esc(post.destination_url)}" placeholder="../magazine/..."><div class="mini-actions">${suggestDest?`<button type="button" data-fill="destination_url" data-value="${esc(suggestDest)}">スポットURLを補完</button>`:''}${post.destination_url?`<a href="${esc(post.destination_url)}" target="_blank" rel="noopener">実ページを開く ↗</a>`:''}</div></label>
  <label class="field full"><span>使用Hero</span><input data-field="hero_ref" value="${esc(post.hero_ref)}" placeholder="../assets/... または Google Places Hero"><div class="mini-actions">${suggestHero?`<button type="button" data-fill="hero_ref" data-value="${esc(suggestHero)}">現在のHeroを補完</button>`:''}</div></label>
  <label class="field"><span>Instagram導線</span><select data-field="instagram_route"><option value=""${!post.instagram_route?' selected':''}>未設定</option><option value="official"${post.instagram_route==='official'?' selected':''}>公式Instagram</option><option value="reel"${post.instagram_route==='reel'?' selected':''}>公式Reel</option><option value="search"${post.instagram_route==='search'?' selected':''}>投稿検索</option><option value="article"${post.instagram_route==='article'?' selected':''}>記事→スポット→Instagram</option><option value="none"${post.instagram_route==='none'?' selected':''}>なし</option></select></label>
  <label class="field"><span>Instagram URL</span><input data-field="instagram_url" value="${esc(post.instagram_url)}" placeholder="https://www.instagram.com/..."><div class="mini-actions">${suggestIg?`<button type="button" data-fill="instagram_url" data-value="${esc(suggestIg)}">登録済み導線を補完</button>`:''}</div></label>
  <label class="field full"><span>Affiliate準備状況</span><input data-field="affiliate_status" value="${esc(post.affiliate_status)}" placeholder="自動判定を使うなら空欄"><div class="readiness">自動判定: <strong>${esc(affStatus)}</strong></div></label>
  <label class="field full"><span>投稿メモ</span><textarea data-field="post_note" rows="3">${esc(post.post_note)}</textarea></label>
  </div></section>
  <section class="section-box result-box"><div class="section-title"><span>PUBLISH / RESULTS</span><strong>投稿実績</strong></div><div class="result-grid">
  ${[['impressions','Impressions'],['reach','Reach'],['saves','Saves'],['shares','Shares'],['replies','Replies'],['site_clicks','Kibun流入'],['outbound_clicks','外部クリック'],['profile_visits','Profile visits']].map(([k,l])=>`<label>${l}<input data-field="result.${k}" inputmode="numeric" value="${esc(post.result?.[k])}"></label>`).join('')}
  </div><label class="field result-notes"><span>結果メモ</span><textarea data-field="result.notes" rows="3">${esc(post.result?.notes)}</textarea></label></section></article>`;}
  function visible(){const q=$('textFilter').value.trim().toLowerCase(),st=$('statusFilter').value,ch=$('channelFilter').value;return state.posts.filter(p=>(st==='all'||p.status===st)&&(ch==='all'||p.channel===ch)&&(!q||`${p.title} ${p.pillar} ${p.spot_id} ${p.destination_url} ${p.copy?.instagram} ${p.copy?.threads}`.toLowerCase().includes(q)));}
  function renderSummary(){const all=state.posts,pub=all.filter(x=>x.status==='published').length,ready=all.filter(x=>x.status==='scheduled'||x.status==='draft').length,missingCopy=all.filter(x=>!x.copy?.instagram||!x.copy?.threads).length,clicks=all.reduce((n,x)=>n+(Number(x.result?.site_clicks)||0),0);$('summary').innerHTML=`<span class="metric"><strong>${all.length}</strong> 投稿</span><span class="metric"><strong>${ready}</strong> 準備中</span><span class="metric"><strong>${pub}</strong> 投稿済み</span><span class="metric"><strong>${missingCopy}</strong> 原稿不足</span><span class="metric"><strong>${clicks}</strong> Kibun流入</span>`;}
  function bind(){document.querySelectorAll('.post-card').forEach(card=>{const id=card.dataset.id;card.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change',()=>{update(id,el.dataset.field,el.value);render();}));card.querySelectorAll('[data-fill]').forEach(btn=>btn.addEventListener('click',()=>{update(id,btn.dataset.fill,btn.dataset.value);render();flash('補完しました')}));card.querySelectorAll('[data-copy-tab]').forEach(btn=>btn.addEventListener('click',()=>{copyTabs[id]=btn.dataset.copyTab;render();}));card.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',()=>{const p=state.posts.find(x=>x.id===id),platform=btn.dataset.platform;const body=p?.copy?.[platform]||'',tags=p?.hashtags?.[platform]||'';copyText(btn.dataset.copy==='all'?[body,tags].filter(Boolean).join('\n\n'):body,btn.dataset.copy==='all'?'原稿＋ハッシュタグをコピーしました':'投稿原稿をコピーしました')}));card.querySelector('[data-remove]')?.addEventListener('click',()=>{if(!confirm('この投稿を削除しますか？'))return;state.posts=state.posts.filter(x=>x.id!==id);persist();render();});});}
  function render(){renderSummary();const rows=visible();$('auditList').innerHTML=rows.length?rows.map(card).join(''):'<article class="post-card"><h2>該当する投稿はありません。</h2></article>';bind();}
  function exportData(){return {version:'20.9.2',exported_at:new Date().toISOString(),posts:state.posts};}
  async function copyText(text,msg){try{await navigator.clipboard.writeText(text)}catch(_e){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}flash(msg);}
  function flash(msg){$('flash').textContent=msg;clearTimeout(flash.t);flash.t=setTimeout(()=>$('flash').textContent='',2400);}
  $('addPost').addEventListener('click',()=>{state.posts.unshift(newPost());persist();$('statusFilter').value='all';render();flash('投稿を追加しました')});
  $('copyJson').addEventListener('click',()=>copyText(JSON.stringify(exportData(),null,2),'設定JSONをコピーしました'));
  $('downloadJson').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'}));a.download='kibun-sns-audit-v20.9.2.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);flash('JSONを保存しました')});
  $('importJson').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!Array.isArray(obj.posts))throw new Error();state=mergeSeed(obj.posts);persist();render();flash('JSONを読み込みました')}catch(_e){flash('JSONを読み込めませんでした')}e.target.value='';});
  $('resetLocal').addEventListener('click',()=>{if(!confirm('SNS Auditの端末保存を初期化しますか？'))return;localStorage.removeItem(KEY);localStorage.removeItem(OLD_KEY);state={posts:clone(seed.posts||[])};render();flash('初期状態に戻しました')});
  $('textFilter').addEventListener('input',render);$('statusFilter').addEventListener('change',render);$('channelFilter').addEventListener('change',render);persist();render();
})();