(function(){
  const seed=window.ODEKAKE_SEED||{spots:[]};
  const cfg=window.KIBUN_AFFILIATE_CONFIG||{};
  const KEY='kibun-affiliate-audit-v1';
  const PROVIDERS={
    ozmall:{label:'OZmall',domain:'ozmall.co.jp',linkswitch:true},
    ikyu_restaurant:{label:'一休.comレストラン',domain:'restaurant.ikyu.com',linkswitch:true},
    ikyu:{label:'一休.com',domain:'ikyu.com',linkswitch:true},
    jalan:{label:'じゃらんnet',domain:'jalan.net',linkswitch:true},
    jtb:{label:'JTB',domain:'jtb.co.jp',linkswitch:true},
    yahoo_travel:{label:'Yahoo!トラベル',domain:'travel.yahoo.co.jp',linkswitch:true},
    asoview:{label:'アソビュー！',domain:'asoview.com',linkswitch:false},
    ticket:{label:'チケットASP候補',domain:'',linkswitch:false}
  };
  const CANDIDATE_MAP=[
    [/OZmall/i,'ozmall'],[/一休\.comレストラン|一休レストラン/i,'ikyu_restaurant'],[/一休\.com|一休/i,'ikyu'],[/じゃらん/i,'jalan'],[/JTB/i,'jtb'],[/Yahoo/i,'yahoo_travel'],[/アソビュー/i,'asoview'],[/国内レジャーチケットASP|チケットASP/i,'ticket']
  ];
  let local=load();
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
  function persist(){localStorage.setItem(KEY,JSON.stringify(local));}
  function providerCandidates(spot){const out=[];(spot?.monetization?.channel_candidates||[]).forEach(text=>CANDIDATE_MAP.forEach(([re,key])=>{if(re.test(text)&&!out.includes(key))out.push(key)}));[...(cfg.links?.[spot.spot_id]||[]),...(cfg.sourceLinks?.[spot.spot_id]||[])].forEach(x=>{if(x?.provider&&PROVIDERS[x.provider]&&!out.includes(x.provider))out.push(x.provider)});return out;}
  function inferIntent(spot){const cats=[spot.category_primary,...(spot.categories||[])].join('|').toLowerCase();if(spot.overnight||/hotel|stay|ryokan|resort/.test(cats)&&!/hotel_lounge/.test(cats))return'stay';if(/food|cafe|restaurant|afternoon_tea|hotel_lounge|dining/.test(cats))return'food';return'experience';}
  function sourceSeed(spotId,provider){return (cfg.sourceLinks?.[spotId]||[]).find(x=>x.provider===provider)||null;}
  function manualSeed(spotId,provider){return (cfg.links?.[spotId]||[]).find(x=>x.provider===provider)||null;}
  function stateFor(spotId,provider){const key=spotId+'::'+provider;const saved=local[key]||{};const src=sourceSeed(spotId,provider);const manual=manualSeed(spotId,provider);return {source_url:saved.source_url??src?.url??'',manual_url:saved.manual_url??manual?.url??'',seedSource:Boolean(src?.url),live:Boolean(manual&&(manual.url||manual.rawHtml)),dirty:Boolean(local[key])};}
  function saveField(spotId,provider,field,value){const key=spotId+'::'+provider;local[key]={...(local[key]||{}),[field]:value.trim()};if(!local[key].source_url&&!local[key].manual_url)delete local[key];persist();render();flash('保存しました');}
  function providerOptions(){const select=$('providerFilter');select.innerHTML=Object.entries(PROVIDERS).filter(([k])=>k!=='ticket').map(([k,v])=>`<option value="${k}"${k==='ozmall'?' selected':''}>${v.label}</option>`).join('')+'<option value="all">すべて</option>';}
  function candidateRows(){return seed.spots.filter(s=>['A','B'].includes(s?.monetization?.affiliate_fit||'')&&providerCandidates(s).length);}
  function currentFilters(){return {q:$('textFilter').value.trim().toLowerCase(),provider:$('providerFilter').value,fit:$('fitFilter').value,status:$('statusFilter').value};}
  function statusFor(st,provider){if(st.live)return'live';if(st.source_url&&PROVIDERS[provider]?.linkswitch&&!cfg.linkSwitch?.tagInstalled)return'waiting';if(st.source_url)return'source';return'missing';}
  function statusLabel(st,provider){const status=statusFor(st,provider);return {live:'本番リンク済み',waiting:'LinkSwitch待ち',source:'元URLあり',missing:'未設定'}[status];}
  function visibleRows(){const f=currentFilters();const rows=[];candidateRows().forEach(spot=>{let ps=providerCandidates(spot);if(f.provider!=='all')ps=ps.filter(p=>p===f.provider);if(!ps.length)return;if(f.fit!=='all'&&spot.monetization.affiliate_fit!==f.fit)return;if(f.q&&!`${spot.spot_id} ${spot.name} ${spot.city||''}`.toLowerCase().includes(f.q))return;ps.forEach(provider=>{const st=stateFor(spot.spot_id,provider);if(f.status!=='all'&&statusFor(st,provider)!==f.status)return;rows.push({spot,provider,st});});});return rows;}
  function searchUrl(spot,provider){const d=PROVIDERS[provider]?.domain;if(!d)return `https://www.google.com/search?q=${encodeURIComponent(spot.name+' 予約')}`;return `https://www.google.com/search?q=${encodeURIComponent('site:'+d+' '+spot.name)}`;}
  function cardHtml(group){const spot=group.spot;const fit=spot.monetization.affiliate_fit;const providers=group.rows.map(r=>r.provider);return `<article class="audit-card"><div class="card-head"><div><span class="spot-id">${esc(spot.spot_id)}</span><h2>${esc(spot.name)}</h2><div class="place">${esc(spot.city||spot.prefecture||'')}</div></div><span class="chip fit-a">FIT ${esc(fit)}</span></div><div class="chips">${providers.map(p=>{const st=stateFor(spot.spot_id,p);const status=statusFor(st,p);return `<span class="chip ${status}">${esc(PROVIDERS[p]?.label||p)} · ${statusLabel(st,p)}</span>`}).join('')}</div>${group.rows.map(r=>providerEditor(spot,r.provider,r.st)).join('')}<div class="official">公式：<a href="${esc(spot.official_url||'#')}" target="_blank" rel="noopener">${esc(spot.official_url||'未登録')}</a></div></article>`;}
  function providerEditor(spot,provider,st){const meta=PROVIDERS[provider]||{label:provider};const linkSwitchHint=meta.linkswitch?'通常ページURLでOK':'必要なら手動アフィリエイトURL';return `<div class="provider-editor" data-spot="${esc(spot.spot_id)}" data-provider="${esc(provider)}"><div class="provider-name">${esc(meta.label)}<br><small>${esc(linkSwitchHint)}</small></div><div class="fields"><div class="field-row"><span>元URL</span><input data-field="source_url" value="${esc(st.source_url)}" placeholder="https://..."><a class="open-btn" href="${searchUrl(spot,provider)}" target="_blank" rel="noopener">${esc(meta.label)}で探す ↗</a></div><div class="field-row"><span>手動Affiliate</span><input data-field="manual_url" value="${esc(st.manual_url)}" placeholder="LinkSwitch非対応時のみ"><span></span></div></div></div>`;}
  function render(){const rows=visibleRows();const grouped=[];rows.forEach(r=>{let g=grouped.find(x=>x.spot.spot_id===r.spot.spot_id);if(!g){g={spot:r.spot,rows:[]};grouped.push(g)}g.rows.push(r)});$('auditList').innerHTML=grouped.length?grouped.map(cardHtml).join(''):'<article class="audit-card"><h2>該当する候補はありません。</h2><p class="place">フィルターを変えてみてください。</p></article>';const all=candidateRows();const configured=rows.filter(r=>r.st.source_url||r.st.live).length;const missing=rows.filter(r=>!r.st.source_url&&!r.st.live).length;$('summary').innerHTML=`<span class="metric"><strong>${grouped.length}</strong> スポット表示</span><span class="metric"><strong>${rows.length}</strong> Provider候補</span><span class="metric"><strong>${configured}</strong> 設定あり</span><span class="metric"><strong>${missing}</strong> 未設定</span><span class="metric">全候補 ${all.length}スポット</span>`;bindInputs();}
  function bindInputs(){document.querySelectorAll('.provider-editor input[data-field]').forEach(input=>{input.addEventListener('change',e=>{const box=e.target.closest('.provider-editor');saveField(box.dataset.spot,box.dataset.provider,e.target.dataset.field,e.target.value)})});}
  function exportData(){const source_link_overrides={},manual_link_overrides={};candidateRows().forEach(spot=>providerCandidates(spot).forEach(provider=>{const st=stateFor(spot.spot_id,provider);if(st.source_url)(source_link_overrides[spot.spot_id]??=[]).push({provider,intent:inferIntent(spot),scope:'spot',url:st.source_url,label:`${PROVIDERS[provider]?.label||provider}で予約を見る`});if(st.manual_url)(manual_link_overrides[spot.spot_id]??=[]).push({provider,intent:inferIntent(spot),scope:'spot',url:st.manual_url,label:`${PROVIDERS[provider]?.label||provider}で予約を見る`})}));return {exported_at:new Date().toISOString(),source_link_overrides,manual_link_overrides};}
  async function copyText(text,msg){try{await navigator.clipboard.writeText(text);flash(msg)}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();flash(msg)}}
  function rowsTsv(rows){return ['spot_id\tname\tprovider\turl'].concat(rows.filter(r=>r.st.source_url).map(r=>[r.spot.spot_id,r.spot.name,PROVIDERS[r.provider]?.label||r.provider,r.st.source_url].join('\t'))).join('\n');}
  function missingTsv(rows){return ['spot_id\tname\tprovider\tsearch_url'].concat(rows.filter(r=>!r.st.source_url&&!r.st.live).map(r=>[r.spot.spot_id,r.spot.name,PROVIDERS[r.provider]?.label||r.provider,searchUrl(r.spot,r.provider)].join('\t'))).join('\n');}
  function flash(msg){$('flash').textContent=msg;clearTimeout(flash.t);flash.t=setTimeout(()=>$('flash').textContent='',2500)}
  function importData(obj){const src=obj?.source_link_overrides||{},man=obj?.manual_link_overrides||{};Object.entries(src).forEach(([sid,arr])=>(arr||[]).forEach(x=>{const key=sid+'::'+x.provider;local[key]={...(local[key]||{}),source_url:x.url||''}}));Object.entries(man).forEach(([sid,arr])=>(arr||[]).forEach(x=>{const key=sid+'::'+x.provider;local[key]={...(local[key]||{}),manual_url:x.url||''}}));persist();render();flash('JSONを読み込みました')}
  function checkProbe(){const a=$('linkSwitchProbe'),out=$('linkSwitchProbeStatus');if(!a||!out)return;const href=a.href||'';const ok=/dalr\.valuecommerce\.com/i.test(href);out.textContent=ok?'OK · ValueCommerceリンクに変換されています':'未変換 · 提携状況を確認して数秒後に再試行';out.style.color=ok?'var(--green)':'var(--accent)';}function init(){providerOptions();const ready=Boolean(cfg.linkSwitch?.enabled&&cfg.linkSwitch?.tagInstalled);$('switchStatus').textContent=ready?'ON · 自動変換対象':'OFF · JSタグ待ち';$('switchStatus').style.color=ready?'var(--green)':'var(--accent)';$('switchNote').textContent=ready?'対応Providerの元URLは公開画面でLinkSwitch変換対象です。':'今は監査・元URL収集だけ行います。公開画面にはLinkSwitch用の元URLは出ません。';['textFilter','providerFilter','fitFilter','statusFilter'].forEach(id=>$(id).addEventListener(id==='textFilter'?'input':'change',render));$('checkLinkSwitch')?.addEventListener('click',checkProbe);setTimeout(checkProbe,2200);$('copyProviderTsv').addEventListener('click',()=>copyText(rowsTsv(visibleRows()),'元URL一覧をコピーしました'));$('copyMissing').addEventListener('click',()=>copyText(missingTsv(visibleRows()),'未設定一覧をコピーしました'));$('copyJson').addEventListener('click',()=>copyText(JSON.stringify(exportData(),null,2),'設定JSONをコピーしました'));$('downloadJson').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kibun-affiliate-overrides.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);flash('JSONを保存しました')});$('importJson').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{importData(JSON.parse(await f.text()))}catch(err){flash('JSONを読み込めませんでした')}e.target.value=''});render();}
  init();
})();