(()=>{
const seed=window.ODEKAKE_SEED||{spots:[]},dataset=window.KIBUN_PERFORMANCES||{performances:[]};const spots=seed.spots||[],byId=Object.fromEntries(spots.map(s=>[s.spot_id,s]));const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const labels={all:'All',ballet:'Ballet',opera:'Opera',musical:'Musicals',theater:'Theatre',kabuki:'Kabuki',noh_kyogen:'Noh & Kyogen',classical:'Classical',dance:'Dance',live:'Live music',family:'Family'};const order=['all','ballet','opera','musical','theater','kabuki','noh_kyogen','classical','dance','live','family'];const areas=[['all','All'],['tokyo','Tokyo'],['kanagawa','Kanagawa']];const whens=[['all','All upcoming'],['30','Next 30 days'],['90','Next 90 days']];let genre=new URLSearchParams(location.search).get('genre')||'all',area=new URLSearchParams(location.search).get('area')||'all',when='all';
const today=(()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`})();const parse=s=>new Date(`${s}T00:00:00`);const enName=s=>s?.i18n?.en?.name||s?.name||'Venue';function fmt(a,b){const x=parse(a),y=parse(b||a),o={month:'short',day:'numeric'};return a===(b||a)?x.toLocaleDateString('en-US',o):`${x.toLocaleDateString('en-US',o)} – ${y.toLocaleDateString('en-US',o)}`}
function items(){return dataset.performances.filter(p=>(p.end_date||p.start_date)>=today).sort((a,b)=>a.start_date.localeCompare(b.start_date)||String(pTitle(a)).localeCompare(pTitle(b)))}function pTitle(p){return p.title_en||p.title}
function matches(p){const s=byId[p.venue_spot_id]||{};if(genre!=='all'&&p.genre!==genre)return false;if(area==='tokyo'&&s.prefecture!=='東京都')return false;if(area==='kanagawa'&&s.prefecture!=='神奈川県')return false;if(when!=='all'){const lim=new Date();lim.setHours(0,0,0,0);lim.setDate(lim.getDate()+Number(when));if(parse(p.start_date)>lim)return false;}const q=$('performanceSearch').value.trim().toLowerCase();return !q||`${p.title} ${p.title_en||''} ${s.name||''} ${enName(s)}`.toLowerCase().includes(q)}
function filters(){$('performanceGenreFilters').innerHTML=order.map(k=>`<button type="button" class="performance-filter-chip ${genre===k?'active':''}" data-genre="${k}">${labels[k]}</button>`).join('');$('performanceAreaFilters').innerHTML=areas.map(([k,l])=>`<button type="button" class="performance-filter-chip ${area===k?'active':''}" data-area="${k}">${l}</button>`).join('');$('performanceWhenFilters').innerHTML=whens.map(([k,l])=>`<button type="button" class="performance-filter-chip ${when===k?'active':''}" data-when="${k}">${l}</button>`).join('');document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{genre=b.dataset.genre;filters();render()});document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{area=b.dataset.area;filters();render()});document.querySelectorAll('[data-when]').forEach(b=>b.onclick=()=>{when=b.dataset.when;filters();render()})}
function card(p){const s=byId[p.venue_spot_id]||{};return `<article class="performance-hub-card"><div class="performance-date-block"><b>${esc(fmt(p.start_date,p.end_date))}</b><span>${esc(labels[p.genre]||p.genre)}</span></div><div class="performance-card-copy"><small>${esc(s.i18n?.en?.city||s.city||'')} · ${esc(enName(s))}</small><h3>${esc(pTitle(p))}</h3>${p.schedule_summary?`<p>${esc(p.schedule_summary)}</p>`:''}<div class="performance-card-tags">${p.duration_minutes?`<span>~${Math.round(p.duration_minutes/5)*5} min</span>`:''}${p.language_note?`<span>${esc(p.language_note)}</span>`:''}${p.age_note?`<span>${esc(p.age_note)}</span>`:''}${p.childcare===true?'<span>Childcare info</span>':''}</div></div><div class="performance-card-actions"><a class="outline-btn" href="/en/?spot=${encodeURIComponent(s.spot_id)}&source=performance">Venue</a><a class="primary-link" href="${esc(p.official_url||s.official_url||'#')}" target="_blank" rel="noopener">Official details →</a></div></article>`}
function render(){const a=items().filter(matches);$('performanceCount').textContent=`${a.length} performance${a.length===1?'':'s'}`;$('performanceGrid').innerHTML=a.map(card).join('');$('performanceEmpty').hidden=a.length>0}$('performanceSearch').addEventListener('input',render);filters();render();
})();
